handles = ["@nytimes",	"@maggieNYT",	"@lpolgreen",	"@brianstelter",	"@Sulliview",	"@NateSilver538",
           "@NewYorker",	"@BarackObama",	"@samdolnick",	"@sewellchan",	"@carolynryan",	"@mikiebarb",	"@SamSifton",
           "@marclacey",	"@carr2n",	"@rcallimachi",	"@DLeonhardt",	"@romenesko",	"@Fahrenthold",	"@nycjim",
           "@fisheri",	"@cjchivers",	"@GlennThrush",	"@nickconfessore",	"@peterbakernyt",	"@deanbaquet",
           "@billkeller2014",	"@UpshotNYT",	"@JillAbramson",	"@NickKristof",	"@jmartNYT",	"@jswatz",
           "@palafo",	"@cliffordlevy",	"@ezraklein",	"@michaelluo",	"@AP",	"@fmanjoo",	"@realDonaldTrump",
           "@jodikantor",	"@washingtonpost",	"@ProPublica",	"@damiencave",	"@jimrutenberg",	"@HillaryClinton",
           "@WSJ",	"@jakesilverstein",	"@sarahlyall",	"@AshleyRParker",	"@juliebosman",	"@NYTFridge",
           "@BuzzFeedBen",	"@michikokakutani",	"@EricLiptonNYT",	"@HirokoTabuchi",	"@mikeallen",
           "@amychozick",	"@meslackman",	"@nytmike",	"@alexburnsNYT",	"@jennydeluxe",	"@JenniferPreston",
           "@paulkrugman",	"@nytimesworld",	"@SopanDeb",	"@jackshafer",	"@amyoleary",	"@TheAtlantic",
           "@NiemanLab",	"@TheOnion",	"@jaketapper",	"@NYTnickc",	"@nytpolitics",	"@POTUS",	"@NYTMetro",
           "@adamnagourney",	"@nytopinion",	"@grynbaum",	"@NYTmag",	"@motokorich",	"@ravisomaiya",	"@POTUS44",
           "@MarkLeibovich",	"@StephenAtHome",	"@liamstack",	"@aoscott",	"@FrankBruni",	"@ABarnardNYT",	"@peterlattman",
           "@lisatozzi",	"@politico",	"@lexim",	"@PostBaron",	"@PamelaPaulNYT",	"@susanchira",	"@shearm",
           "@Longreads",	"@DanBarryNYT",	"@rudoren",	"@jwpetersNYT",	"@RyanLizza",	"@emilynussbaum",	"@EllenBarryNYT",
           "@BBCBreaking",	"@Nate_Cohn",	"@BCAppelbaum",	"@blakehounshell",	"@TheEconomist",	"@daveweigel",	"@NPR",
           "@SangerNYT",	"@adamliptak",	"@Julesm_b",	"@cnnbrk",	"@davidfolkenflik",	"@ditzkoff",	"@SarahMaslinNir",
           "@jayrosen_nyu",	"@nybooks",	"@sergenyt",	"@Yamiche",	"@powellnyt",	"@jeligon",	"@NYTNational",	"@andyrNYT",
           "@mattfleg",	"@FiveThirtyEight",	"@Wendo20",	"@Max_Fisher",	"@jonathanweisman",	"@michaelroston",	"@NYTimesPR",
           "@crampell",	"@NYTArchives",	"@NYMag",	"@ddknyt",	"@nycscribe",	"@chrislhayes",	"@davidfrum",	"@Choire",
           "@mattbpurdy",	"@juliehdavis",	"@Poynter",	"@WhiteHouse",	"@pete_wells",	"@voxdotcom",	"@ggreenwald",
           "@jestei",	"@katierogers",	"@alanblinder",	"@bydanielvictor",	"@MikeIsaac",	"@rickberke",	"@viaSimonRomero",
           "@JeffreyGoldberg",	"@Reuters",	"@jeffzeleny",	"@poniewozik",	"@OnThisDayNYT",	"@JBennet",	"@Slate",
           "@charlie_savage",	"@mlcalderone",	"@adamgoldmanNYT",	"@emilysteel",	"@louisestory",	"@BillClinton",
           "@nickbilton",	"@declanwalsh",	"@melbournecoal",	"@MarkLandler",	"@tarangoNYT",	"@davidaxelrod",
           "@bittman",	"@jackhealyNYT",	"@kimseverson",	"@AnnieLowrey",	"@MarkMazzettiNYT",	"@ScottShaneNYT",	"@TomJolly",
           "@PressSec",	"@DwightGarner",	"@NYTOnIt",	"@maureendowd",	"@VivianHYee",	"@randyNYT",	"@jasondhorowitz",
           "@nhannahjones",	"@gabrielsherman",	"@lheron",	"@andylocal",	"@JamesFallows",	"@susannecraig",
           "@coopnytimes",	"@ObamaWhiteHouse",	"@juliaioffe",	"@Wesley_Morris",	"@hillhulse",	"@dickstevenson",
           "@Rueby",	"@FrancesRobles",	"@CNN",	"@BBCWorld",	"@andrewrsorkin",	"@tanzinavega",	"@monicadavey1",
           "@nxthompson",	"@campbellnyt",	"@KFILE",	"@guardian",	"@clairecm",	"@BeschlossDC",	"@LaSharah",
           "@felixsalmon",	"@mattyglesias",	"@tripgabriel",	"@RachelDonadio",	"@greenhousenyt",	"@jbarro",
           "@amandahess",	"@AllMattNYT",	"@maddow",	"@thomaskaplan",	"@jonathanlandman",	"@comradewong",	"@jenny8lee",
           "@jonathanmahler",	"@JimBYardley",	"@amy_harmon",	"@frankrichny",	"@nytvideo",	"@lizzieohreally",
           "@CoralMDavenport",	"@costareports",	"@SherylNYT",	"@PhilipRucker",	"@Snowden",	"@jimdao",	"@nytimesphoto",
           "@nkulish",	"@DylanByers",	"@pvolpe",	"@NYTMinusContext",	"@dansaltzstein",	"@ShreeyaSinha",	"@monicadrake",
           "@mattapuzzo",	"@ClydeHaberman",	"@Rogene",	"@jonathanchait",	"@daniellemattoon",	"@rupertmurdoch",	"@fstonenyc",
           "@TylerHicksPhoto",	"@thegarance",	"@BreakingNews",	"@WesleyLowery",	"@patrickhealynyt",	"@deanemurphy",
           "@StevenErlanger",	"@AlecMacGillis",	"@SashaK",	"@nytfood",	"@RobertMackey",	"@page88",	"@jimdwyernyt",
           "@soledadobrien",	"@gabrieldance",	"@HugoLindgren",	"@EricSchmittNYT",	"@jessemckinley",	"@ByFernandaS",
           "@stephcliff",	"@nytham",	"@jonfavs",	"@jennymedina",	"@pilhofer",	"@JohnBranchNYT",	"@chucktodd",	"@emmagf",
           "@tackettdc",	"@TheDailyShow",	"@nytgraphics",	"@NYCcyn",	"@ronlieber",	"@nicoleperlroth",	"@julieturkewitz",
           "@nytmedia",	"@gailcollins",	"@nytimesarts",	"@jelani9",	"@CillizzaCNN",	"@karaswisher",	"@lenadunham",	"@MikeBloomberg",
           "@Pontifex",	"@Neil_Irwin",	"@Alissanyt",	"@kevinroose",	"@Lin_Manuel",	"@CJR",	"@mollyesque",	"@jdavidgoodman",
           "@caraNYT",	"@hfairfield",	"@RBlumenstein",	"@Medium",	"@joshtpm",	"@Gawker",	"@NYCMayor",	"@nytimesbooks",
           "@MichaelPaulson",	"@dannyhakim",	"@koblin",	"@pourmecoffee",	"@readercenter",	"@ThomasErdbrink",	"@LizetteScribe",
           "@CharlesMBlow",	"@SarahKSilverman",	"@herszenhorn",	"@dougmillsnyt",	"@ElisGoodridge",	"@ErikWemple",	"@eosnos",
           "@DavidBarboza2",	"@jbsgreenberg",	"@TimOBrien",	"@BV", 	"@Gadfly",	"@thejoesexton",	"@JenSeniorNY",
           "@PreetBharara",	"@SteveMartinToGo",	"@mosisecret",	"@stavernise",	"@RebeccaRuiz",	"@mccanner",	"@noamscheiber",
           "@BumillerNYT",	"@Duenes",	"@mattdpearce",	"@davidwchen",	"@BrentNYT",	"@halbfinger",	"@rpogrebin",	"@kimmelman",
           "@alexmaccallum",	"@caseysjournal",	"@rtraister",	"@andersoncooper",	"@KirkSemple",	"@jbouie",	"@PGourevitch",
           "@latimes",	"@Graham_Bowley",	"@Reading_ln",	"@KatyTurNBC",	"@pkhoury_nyt",	"@SenSanders",	"@kseelye",	"@KeithBradsher",
           "@ktumulty",	"@SteveEder",	"@darlin",	"@davidjoachim",	"@longform",	"@gerrymullany",	"@FLOTUS",	"@NinaBernstein1",
           "@Revkin",	"@jacobwe",	"@sree",	"@WIRED",	"@DesNYT",	"@joncaramanica",	"@katephillips",	"@amyvirshup",
           "@andreafelliott",	"@tnyCloseRead",	"@AlMitc",	"@BraddJaffy",	"@derekwillis",	"@Gothamist",	"@sbg1",	"@wikileaks",
           "@greghoward88",	"@karenzraick",	"@dianabhenriques",	"@JohnJHarwood",	"@alexismadrigal",	"@nytimesbusiness",	"@Awl",
           "@NYTBen",	"@emilybell",	"@dchangnyt",	"@samanthastorey",	"@gettleman",	"@abbygoodnough",	"@sullydish",
           "@DavidFurstNYT",	"@kfahim",	"@itscaitlinhd",	"@mega2e",	"@BuzzFeed",	"@SCOTUSblog",	"@AmbPower44",
           "@sangerkatz",	"@susanorlean",	"@NYTSports",	"@mschwirtz",	"@cslwrites",	"@VanityFair",	"@iamjohnoliver",
           "@hellobuglers",	"@jessicalustig",	"@emilybazelon",	"@DavidGrann",	"@MichelleObama",	"@SlaughterAM",	"@parisreview",
           "@janinegibson",	"@Jeffdelviscio",	"@tminsberg",	"@sona",	"@ConanOBrien",	"@BorowitzReport",	"@Anthony",
           "@HernandezJavier",	"@ajchavar",	"@katetaylornyt",	"@spaydl",	"@kzernike",	"@neiltyson",	"@rachelswarns",
           "@vikasbajaj",	"@MarshallProj",	"@FLOTUS44",	"@Susan_Edgerley",	"@coreykilgannon",	"@KevinQ",	"@chaughney",
           "@EnnisNYT",	"@helenecooper",	"@taffyakner",	"@catrineinhorn",	"@Liz_A_Harris",	"@DVNJr",	"@kenvogel",
           "@jimschachter",	"@HuffPost",	"@migold",	"@AshleyAtTimes",	"@PressSec44",	"@business",	"@susandominus",
           "@SenWarren",	"@rickgladstone",	"@arappeport",	"@BillGates",	"@jeremybowers",	"@gabrielsnyder",	"@bankonjustin",
           "@jonathanellis",	"@JeffreyToobin",	"@moorehn",	"@thedailybeast",	"@TroyEricG",	"@radhikajones",	"@brainpicker",
           "@nytlizrobbins",	"@MotherJones",	"@lauriegnyt",	"@SimoneSOliver",	"@DanBilefsky",	"@ChelseaClinton",	"@cduhigg",
           "@juliamoskin",	"@Atul_Gawande",	"@drewvigal",	"@AdrianChen",	"@HarrisAimee",	"@HannaIngber",	"@Scaramucci",
           "@mattbai",	"@KBAndersen",	"@observer",	"@Jo_Becker",	"@KatrinaNation",	"@NeilMacFarquhar",	"@dagnysalas",
           "@anniecorreal",	"@AnnaHolmes",	"@AlexandraJacobs",	"@parul_sehgal",	"@hannahdreier",	"@AJEnglish",
           "@BenWeiserNYT",	"@ClaraJeffery",	"@JustinWolfers",	"@markoff",	"@marknyt",	"@KellyannePolls",	"@WNYC",
           "@gilbertcruz",	"@ThisAmerLife",	"@jessbidgood",	"@BretStephensNYT",	"@MWilsonNYT",	"@S_Evangelina",
           "@camanpour",	"@BrianLehrer",	"@puiwingtam",	"@pmarca",	"@samstein",	"@mannyNYT",	"@ForeignPolicy",
           "@panphil",	"@dionnesearcey",	"@SuzanneSpecNYT",	"@jdawsey1",	"@Comey",	"@DouthatNYT",	"@DavidCornDC",
           "@laurenzcollins",	"@fionaspruill",	"@VP",	"@jazzedloon",	"@jess7bennett",	"@jennyschuessler",	"@jdickerson",
           "@dabeard",	"@stevenleemyers",	"@SominiSengupta",	"@anamariecox",	"@danbalz",	"@ariannahuff",	"@StateDept",
           "@sethmnookin",	"@MTA",	"@RonanFarrow",	"@Applebome",	"@andrewkueneman",	"@Olivianuzzi",	"@dgelles",	"@londonoe",
           "@marypilon",	"@GiniaNYT",	"@MarkHalperin",	"@CoryBooker",	"@Shteyngart",	"@mashable",	"@NYTScience",
           "@jbenton",	"@ZekeJMiller",	"@joepompeo",	"@nypost",	"@andrewkeh",	"@Pogue",	"@tysone",	"@ThePlumLineGS",
           "@TIME",	"@mtaibbi",	"@qz",	"@RaR",	"@danielle_ivory",	"@AoDespair",	"@heathertal",	"@NYCMayorsOffice",	"@NYGovCuomo",
           "@arusbridger",	"@RosieGray",	"@ianbremmer",	"@rachelsklar",	"@jimwindolf",	"@prashantrao",	"@heislerphoto",
           "@lrozen",	"@benjaminwittes",	"@lawfareblog",	"@eisingerj",	"@nprpolitics",	"@JeffGordinier",	"@VVFriedman",
           "@taraparkerpope",	"@azamsahmed",	"@JulietMacur",	"@xanalter",	"@jotted",	"@brianmrosenthal",	"@NYCTSubway",
           "@perezpena",	"@BernieSanders",	"@NYTimesCohen",	"@PekingMike",	"@lynseyaddario",	"@gwenifill",
           "@HowardKurtz",	"@CBSNews",	"@kitty_bennett",	"@m_delamerced",	"@RichardFausset",	"@scootes",	"@politicony",
           "@marcatracy",	"@jwherrman",	"@cshirky",	"@eckholm",	"@michaelpollan",	"@kinseywilson",	"@IvankaTrump",
           "@mccarthyryanj",	"@DougSchorzman",	"@almarlatour",	"@JamesEstrin",	"@NPRinskeep",	"@patkiernan",	"@pewresearch",
           "@MelissaClark",	"@wpjenna",	"@AdamBBryant",	"@mindykaling",	"@danwakin",	"@aellick",	"@mitchellreports",	"@sternbergh",
           "@pbump",	"@billwasik",	"@ellenjpollock1",	"@ChuBailiang",	"@ceciliakang",	"@vulture",	"@JohnCassidy",	"@BuzzFeedNews",
           "@petridishes",	"@MiriamElder",	"@chashomans",	"@JanBenzel",	"@JakeSherman",	"@DeborahAcosta",	"@ShaneGoldmacher",
           "@JamilSmith",	"@GeeDee215",	"@hrw",	"@ABC",	"@TPM",	"@nytimestech",	"@elizabethforma",	"@newrepublic",	"@ashleyfeinberg",
           "@drtimes",	"@samrob12",	"@JesseDrucker",	"@yashar",	"@TinaBrownLM",	"@tomfriedman",	"@JohnKerry",	"@GardinerHarris",
           "@jiatolentino",	"@ForeignAffairs",	"@WRashbaum",	"@CeylanWrites",	"@ksacknyt",	"@Ari_NYT",	"@Watching",	"@ACLU",
           "@bcsolomon",	"@jackiekcalmes",	"@brooksbarnesNYT",	"@nytstevek",	"@mikeabramsnyt",	"@ConorDougherty",
           "@StuartEmmrichNY",	"@katierosman",	"@NoceraBV",	"@ricklyman",	"@ktbenner",	"@SenJohnMcCain",	"@Hadas_Gold",
           "@tejucole",	"@sarahkliff",	"@OHnewsroom",	"@markknoller",	"@NellieBowles",	"@Bourdain",	"@deray",	"@shailadewan",
           "@AGSNYT",	"@irin",	"@swheaton",	"@ericuman",	"@Bencjacobs",	"@elonmusk",	"@kalyTsoto",	"@anniekarni",
           "@jaycaspiankang",	"@rodnordland",	"@tomfeyer",	"@NYTupdates",	"@sethmeyers",	"@azizansari",	"@amandahesser",
           "@AdamSerwer",	"@AKannapell",	"@colsonwhitehead",	"@farrellnyt",	"@attackerman",	"@RohdeD",	"@JoeNBC",	"@iraglass",
           "@DRUDGE_REPORT",	"@DRUDGE",	"@PatcohenNYT",	"@vindugoel",	"@raju",	"@zena_b",	"@Acosta",	"@zseward",
           "@theintercept",	"@reneemurawski",	"@katiezez",	"@FoxNews",	"@jialynnyang",	"@harrisj",	"@farrellreporter",
           "@BillSimmons",	"@JoyAnnReid",	"@BrendanNyhan",	"@NYTeileen",	"@johnleland",	"@DanaGoldstein",	"@MittRomney",
           "@jimmyfallon",	"@NewsHour",	"@JessePesta",	"@SenSchumer",	"@LizSly",	"@JanePerlez",	"@SeinfeldToday",
           "@nicknotned",	"@AnandWrites",	"@DaveSmithNY",	"@jasongay",	"@sapna",	"@arielkaminer",	"@IanTrontz",
           "@thomasfullerNYT",	"@AP_Alerts",	"@petersgoodman",	"@TheStalwart",	"@hblodget",	"@amandacox",	"@joshrogin",
           "@hellerNYT",	"@ianrausten",	"@marcusmabry",	"@sjwilliams",	"@jk_rowling",	"@morningmoneyben",	"@jonleeanderson",
           "@ShaunKing",	"@AzmatZahra",	"@GStephanopoulos",	"@RickHertzberg",	"@magiorNY",	"@jeremyzilar",	"@TheRickWilson",
           "@thehill",	"@pamelacolloff",	"@jonlovett",	"@FareedZakaria",	"@alison_smale",	"@qhardy",	"@tmagazine",
           "@Salon",	"@joecoscarelli",	"@BernsteinJacob",	"@espiers",	"@Grantland33",	"@PeterHamby",	"@docubrent",
           "@AlexVadukul",	"@kljohnso",	"@NASA",	"@NatGeo",	"@henryfountain",	"@mike_pence",	"@mckaycoppins",
           "@kurteichenwald",	"@SteveEngelberg",	"@DavidWDunlap",	"@jpodhoretz",	"@jheil",	"@NYDailyNews",	"@JustinSablich",
           "@BillKristol",	"@JustinHGillis",	"@AndrewJacobsNYT",	"@jdelreal",	"@zeynep",	"@SalmanRushdie",	"@McFaul",	"@edatpost",
           "@amyschumer",	"@pareene",	"@kathrynschulz",	"@vicenews",	"@kemcke",	"@FranklinFoer",	"@amyfiscus",
           "@mairalg",	"@amandataub",	"@melenar",	"@BilldeBlasio",	"@NYPDnews",	"@rgay",	"@DKThomp",	"@NBCNews",
           "@stuartpstevens",	"@Tyrangiel",	"@anildash",	"@nixonron",	"@el_belson",	"@dandrezner",	"@SamBorden",
           "@billmaher",	"@Gladwell",	"@peretti",	"@davidjshipley",	"@dealbook",	"@mmcphate",	"@malachybrowne",
           "@loisbeckett",	"@EricAsimov",	"@daniellerha",	"@JessicaValenti",	"@Kim_Barker",	"@henricauvin",	"@JuliaPrestonNow",
           "@kitastew",	"@Susan_Hennessey",	"@howiewolf",	"@egoode",	"@AndrewDasNYT",	"@amyewalter",	"@RBReich",	"@kleinmatic",
           "@delaney",	"@MerriamWebster",	"@nyguild",	"@FT",	"@johnjcook",	"@JoeKGoldstein",	"@mviser",	"@frontlinepbs",
           "@Variety",	"@mericson",	"@Rebeccamead_NYC",	"@JuddApatow",	"@AFP",	"@jeremyscahill",	"@TheEllenShow",	"@archietse",
           "@chuckstrum",	"@kerrimac",	"@Azi",	"@silviakillings",	"@MujMash",	"@PatrickKingsley",	"@bartongellman",	"@jeffjarvis",
           "@TVietor08",	"@VP44",	"@GlennKesslerWP",	"@jimtankersley",	"@NYTStyles",	"@JoyceCarolOates",	"@fstockman",
           "@MHoppertNYT",	"@NirajC",	"@tatertatiana",	"@sisario",	"@ananavarro",	"@Nataliekitro",	"@CIA",	"@danpfeiffer",
           "@PeterBeinart",	"@megynkelly",	"@waltmossberg",	"@VICE",	"@Twitter",	"@PolitiFact",	"@KenRoth",	"@lavallee",
           "@mathewi",	"@niederme",	"@leslyedavis",	"@JaneMayerNYer",	"@garcia_alexndra",	"@ElBloombito",	"@Deadspin",
           "@intelligencer",	"@pressfreedom",	"@PeteSouza44",	"@nickwingfield",	"@npfandos",	"@dneedleman1",	"@KateAurthur",
           "@ava",	"@Newsweek",	"@thenation",	"@DSlotnik",	"@ssstrom",	"@MaryMSuh",	"@laurenduca",	"@karenyourish",
           "@seanspicer",	"@elopez_nyt",	"@bakeal",	"@davidmwessel",	"@Evan_McMullin",	"@SenGillibrand",	"@ruthreichl",
           "@muckrack",	"@DraperRobert",	"@AmbRice44",	"@algore",	"@JoshuaGreen",	"@doree",	"@darth",	"@bxchen",
           "@EricLichtblau",	"@TayeDiggs",	"@JenniferJJacobs",	"@TheAtlNews",	"@annfriedman",	"@DRUDGE",	"@GovChristie",
           "@emmarieDC",	"@emilyweinstein",	"@shani_o",	"@TimHerrera",	"@NY1",	"@emilymbadger",	"@RosenthalHealth",	"@hamman",
           "@UN",	"@austinramzy",	"@DavidBarstow",	"@willieneuman",	"@acarvin",	"@marcambinder",	"@SpeakerRyan",	"@marcorubio",
           "@sfj",	"@lawrence_wright",	"@portereduardo",	"@gebeloffnyt",	"@nycgov",	"@MarkHarrisNYC",	"@TechCrunch",	"@Harpers",
           "@MC_NYC",	"@ian_urbina",	"@stephronyt",	"@HannaRosin",	"@tejalrao",	"@joedrape",	"@BostonGlobe",	"@Nouriel",
           "@joshkellerjosh",	"@abstractsunday",	"@AlibabaPRGuy",	"@maureenoco",	"@MichaelWolffNYC",	"@NYTObits",	"@dsorbara",
           "@charlesornstein",	"@guardiannews",	"@Grahaphics",	"@max_read",	"@kylegriffin1",	"@tarasbernard",	"@sarahk11",
           "@MattGoldstein26",	"@joshgreenman",	"@DafnaLinzer",	"@Reince",	"@TheTweetOfGod",	"@RachelAbramsNY",	"@DavidClinchNews",
           "@davidplouffe",	"@sissenberg",	"@Austan_Goolsbee",	"@nytimeswell",	"@jack",	"@NancyPelosi",	"@tadfriend",	"@kairyssdal",
           "@JerrySeinfeld",	"@nytimesatwar",	"@diantha",	"@DonaldJTrumpJr",	"@johnwilliamsnyt",	"@_alastair",	"@latimes",
           "@DavanMaharaj",	"@garveymcvg",	"@mattdpearce",	"@shelbygrad",	"@nytimes",	"@hfuhrmann",	"@LAcrimes",	"@LANow",
           "@ronlin",	"@AP",	"@MarcDuvoisin",	"@laura_nelson",	"@tboucherLA",	"@BarackObama",	"@kyoshino",	"@ByMattStevens",
           "@LATimeskraft",	"@katelinthicum",	"@yamphoto",	"@LATstevelopez",	"@AbcarianLAT",	"@anblanx",	"@haileybranson",
           "@mmaltaisLA",	"@karihow",	"@NewYorker",	"@hbecerraLATimes",	"@LATimesFreshInk",	"@LATvives",	"@AliceShort3",
           "@LATSeema",	"@romenesko",	"@washingtonpost",	"@mollyhf",	"@JosephSerna",	"@jtcorrigan",	"@jackfleonard",
           "@katemather",	"@mitrakalita",	"@Laurie_Ochoa",	"@LAObserved",	"@tcurwen",	"@frankshyong",	"@marisagerber",
           "@WSJ",	"@kimmurphy",	"@BobsLAtimes",	"@palewire",	"@latimesphotos",	"@RosannaXia",	"@AlpertReyes",	"@StevePadilla2",
           "@jaweedkaleem",	"@vicjkim",	"@JamesQueallyLAT",	"@ChrisMegerian",	"@LATimescitybeat",	"@emamd",	"@sarahparvini",
           "@francineorr",	"@DanielNMiller",	"@MaeveReston",	"@DianaMarcum",	"@RobertFaturechi",	"@saba_h",	"@ProPublica",	"@cnnbrk",
           "@marymacTV",	"@LATreadersrep",	"@steveclowLA",	"@wjhenn",	"@NPR",	"@markzbarabak",	"@DavidZahniser",	"@bvdbrug",
           "@MatthewLait",	"@SLeasca",	"@jpanzar",	"@MegJamesLAT",	"@kurtstreeter",	"@cathleendecker",	"@jaylclendenin",
           "@brittny_mejia",	"@latimesnational",	"@nicolesantacruz",	"@ashleydunnlat",	"@RaineyTime",	"@joelrubin",	"@TheOnion",
           "@MattHjourno",	"@mazet",	"@thejgold",	"@byandreachang",	"@marthaGroves",	"@MartinBeck",	"@Poynter",	"@CNN",
           "@philwillon",	"@maloym",	"@HillaryClinton",	"@DavidLauter",	"@mateagold",	"@LAJourno",	"@latfoto",	"@NateSilver538",
           "@Davidlaz",	"@villarrealy",	"@alschaben",	"@palomaesquivel",	"@cmaiduc",	"@bposton",	"@montemorin",	"@tonybarboza",
           "@JulieWestfall",	"@maggieNYT",	"@AmyKinLA",	"@PMoneyLA",	"@TrevellAnderson",	"@gtherolf",	"@LATlands",
           "@ezraklein",	"@TheCityMaven",	"@sjceasar",	"@LATgreatreads",	"@KPCC",	"@LAist",	"@sewella",	"@MarkBoster",
           "@mayalau",	"@ScottGloverCNN",	"@mkballinger",	"@brianstelter",	"@StephenAtHome",	"@GenaroMolina47",	"@rgaut999",
           "@finneganLAT",	"@DeborahNetburn",	"@LorraineAli",	"@LATgeoffmohan",	"@skarlamangla",	"@StephenMarble",	"@NiemanLab",
           "@ericgarcetti",	"@Carolyn_Cole",	"@evanhalper",	"@ThatRebecca",	"@jackdolanLAT",	"@JasonBretWells",	"@maryannmeekLAT",
           "@marialaganga",	"@PringleLATimes",	"@RStjohn_latimes",	"@kenbensinger",	"@VeronicaRochaLA",	"@realDonaldTrump",	"@POTUS44",
           "@chadterhune",	"@Fahrenthold",	"@Reuters",	"@austinbeutner",	"@jvgarrison",	"@cindychangLA",	"@latimesent",
           "@luissinco",	"@Slate",	"@LATdatadesk",	"@RaR",	"@AlexLeTellier",	"@dhpierson",	"@WesleyLowery",	"@ashleypowers",
           "@carlosvlozano",	"@gaufre",	"@nigelduara",	"@AliManzano",	"@cindyhively",	"@BBCBreaking",	"@POTUS",	"@JulieMakLAT",
           "@melmason",	"@aminawrite",	"@latimesreaders",	"@byjsong",	"@AlSeibPhoto",	"@TheAtlantic",	"@latimesharriet",
           "@GerrickKennedy",	"@tinasusman",	"@AngelJennings",	"@Jenn_Harris_",	"@RJLosAngeles",	"@photospice",
           "@carr2n",	"@latimespolitics",	"@theCindyCarcamo",	"@WhiteHouse",	"@alexzavis",	"@kchristensenLAT",	"@hiltzikm",
           "@GinaFerazzi",	"@TheEconomist",	"@cmonstah",	"@RFaughnder",	"@pattmlatimes",	"@raablauren",	"@KatieFalkenberg",
           "@jaketapper",	"@lauraelizdavis",	"@rverrier",	"@jarthur47",	"@LATChrisGoffard",	"@guardian",	"@cbellantoni",
           "@kurtisalee",	"@NickKristof",	"@aflores",	"@NRiveraBrooksLA",	"@latpix",	"@ajrod",	"@ObamaWhiteHouse",	"@ByBrianBennett",
           "@WallySkalij",	"@politico",	"@johnmyers",	"@ZeitchikWaPo",	"@JeffreyLAT",	"@mikememoli",	"@latimesfood",	"@LATDoug",
           "@LizOBaylen",	"@adamnagourney",	"@GlennWhipp",	"@PostBaron",	"@mikeallen",	"@bdelossantos1",	"@renelynch",
           "@mymackie",	"@jbogertjr",	"@HawthorneLAT",	"@Sam_Schaefer",	"@soledadobrien",	"@spfeifer22",	"@Longreads",
           "@JAdamsMJS",	"@BillPlaschke",	"@latguild",	"@NBCLA",	"@BBCWorld",	"@TheCDZ",	"@csaillant2",	"@LATimesCityGov",
           "@peard33",	"@LAWeekly",	"@smasunaga",	"@CatHamm",	"@juliedmarquis",	"@newsterrier",	"@lisagirion",	"@KennethTuran",
           "@bryanchanphoto",	"@andersoncooper",	"@khouriandrew",	"@LAMarlaD",	"@2020lens",	"@allisonwisk",	"@obrien",
           "@newton_jim",	"@AlejandroLazo",	"@TheBrianPark",	"@voxdotcom",	"@Sonali_Kohli",	"@Variety",	"@ConanOBrien",
           "@latimesbooks",	"@TIME",	"@nicco",	"@mcgreevy99",	"@LATimesTVLloyd",	"@jenyamato",	"@julie_cart",	"@FancyBethany",
           "@nathanfenno",	"@PeteJamison",	"@LAmag",	"@paigestjohn",	"@ByKellyParker",	"@socalbreeze",	"@MotherJones",	"@KTLA",
           "@MayorOfLA",	"@LATkarenkaplan",	"@JerryBrownGov",	"@daveweigel",	"@jeanmerl",	"@annecusackderk",	"@RickLoomis",
           "@HuffPost",	"@dakotacdsmith",	"@SBengali",	"@swsandell",	"@sarahHwaris",	"@MelMelconPhoto",	"@anthonyjpesce",
           "@Nataliekitro",	"@andreamcastillo",	"@latimesworld",	"@IndieFocus",	"@TeresaWatanabe",	"@JimmyOrr",	"@priyakkumar",
           "@maddow",	"@LisaMascaro",	"@BuzzFeed",	"@paperhaus",	"@lahalw",	"@LAFD",	"@KamalaHarris",	"@amyfiscus",
           "@TheErynBrown",	"@CJR",	"@BobSipchen",	"@jennymedina",	"@RickSerranoLAT",	"@geoffboucher",	"@DebbieGoffa",	"@joemfox",
           "@ryanvmenezes",	"@BuzzFeedBen",	"@JoeBelBruno",	"@latimesbiz",	"@thedailybeast",	"@Russ_Parsons1",	"@tinadaunt",
           "@calvinhom",	"@ReporterClaudia",	"@davidfolkenflik",	"@cparsons",	"@rosslevinsohn",	"@CurbedLA",
           "@NardineSaad",	"@LouisSahagun",	"@latimesvideo",	"@amcovarrubias",	"@LATimesfarmer",	"@jessicagelt",
           "@boxall",	"@LASDHQ",	"@annagorman",	"@joseiswriting",	"@AmyTheHub",	"@geholland",	"@Toddmartens",
           "@Joy_Resmovits",	"@culturemonster",	"@latimespast",	"@ColinCrawford",	"@dbartletti",	"@BreakingNews",
           "@BuzzFeedNews",	"@WIRED",	"@dennisjromero",	"@TheDailyShow",	"@beth_shuster",	"@debvankin",	"@NicoleCharky",
           "@AleneTchek",	"@dillonliam",	"@latimesmuskal",	"@ABC7",	"@RVartabedian",	"@SteveMartinToGo",	"@leeromney",
           "@nateog",	"@countkwokula",	"@RichMarosi",	"@billkeller2014",	"@FiveThirtyEight",	"@charlesornstein",	"@BillClinton",
           "@OHnewsroom",	"@jayrosen_nyu",	"@kirkjim12",	"@jasonfelch",	"@LilEdit",	"@pattonoswalt",	"@davidcolker",
           "@latimespugmire",	"@boreskes",	"@corinaknoll",	"@THR",	"@JimPuzzanghera",	"@KateAurthur",	"@GlennThrush",	"@ByShanLi",
           "@LAhistory",	"@JBFlint",	"@erskinetimes",	"@joemozingo",	"@ABC",	"@FLOTUS",	"@DylanByers",	"@Gawker",	"@sarahdwire",
           "@SarahKSilverman",	"@mashable",	"@ktpassantino",	"@latimesmovies",	"@paulkrugman",	"@Sulliview",	"@latimessports",
           "@BillGates",	"@BarbaraDemick",	"@busblog",	"@latimesscience",	"@rljourno",	"@latimesopinion",	"@misterfleming",
           "@noellecarter",	"@myung_chun",	"@RobertMeeksRT",	"@chavismophoto",	"@costareports",	"@kcrw",	"@tiffkhsu",
           "@AlanaSemuels",	"@AugustBrown",	"@PopHiss",	"@davidaxelrod",	"@CBSLA",	"@EvanWagstaff",	"@RyanLizza",	"@AMSimmons1",
           "@muckrack",	"@dylanohernandez",	"@NBCNews",	"@schwanksta",	"@APStylebook",	"@jimmyfallon",	"@melissaetehad",	"@RobynDixon_LAT",
           "@LATpoliticsCA",	"@ARTschorn",	"@lfung",	"@rnordwind",	"@neiltyson",	"@BillShaikin",	"@FLOTUS44",	"@DowntownNews",
           "@Noahbierman",	"@MediaBlotter",	"@GustavoArellano",	"@nycjim",	"@mikaelwood",	"@clairenoland",	"@omgponiez",
           "@boazherzog",	"@CIRonline",	"@PressSec",	"@longdrivesouth",	"@stevesaldivar",	"@Joypress",	"@chucktodd",
           "@GottliebJeff",	"@RepAdamSchiff",	"@CShalby",	"@kbui1",	"@nickconfessore",	"@Patt_Morrison",	"@davidfrum",
           "@JillMarieJones",	"@meerabee",	"@JGHorn",	"@JustinCChang",	"@latimestech",	"@ranoa",	"@SenWarren",	"@CBSNews",
           "@LAPDHQ",	"@CityAttorneyLA",	"@ggreenwald",	"@chrislhayes",	"@CillizzaCNN",	"@LAScanner",	"@DawnC331",	"@LATcompanytown",
           "@joshrottenberg",	"@RichardFausset",	"@lacrepat",	"@bretisrael",	"@photoandmac",	"@BeeCeeLive",	"@nytimesphoto",
           "@azizansari",	"@DrLucyJones",	"@kdoctor",	"@longform",	"@LAWilliams30",	"@hugomartin",	"@mauradolan",	"@James_Barragan",
           "@lewisdvorkin",	"@patrickkevinday",	"@latimeshealth",	"@LACoFDPIO",	"@tennyt",	"@LACo_FD",	"@mindykaling",	"@michaelwhitley",
           "@seangreene89",	"@benmuessig",	"@anniezyu",	"@lendegroot",	"@pewresearch",	"@nprpolitics",	"@JTanfani",	"@joemmathews",
           "@latams",	"@benfritz",	"@MeredithBlake",	"@lstomsl",	"@jazmineulloa",	"@NASA",	"@TheEllenShow",	"@MichelleObama",
           "@JRKaiman",	"@latimesmost",	"@LATimesSkelton",	"@LATbermudez",	"@rogervincent",	"@MdellW",	"@KNX1070",	"@deanbaquet",
           "@rdaphoto63",	"@frontlinepbs",	"@cjchivers",	"@ktumulty",	"@VanityFair",	"@anthonyyork49",	"@khennessey",
           "@peterbakernyt",	"@LarryJayGordon",	"@latimeslarry",	"@NoamLevey",	"@LATshowtracker",	"@dsarno",	"@lighthausinc",
           "@tonyperrysd",	"@HelloLATimes",	"@friedmanphoto",	"@DRUDGE_REPORT",	"@DRUDGE",	"@kyleykim",	"@SCOTUSblog",
           "@DoyleMcManus",	"@AgrawalNina",	"@AndrewTangel",	"@KFILE",	"@MarcLifsher",	"@jmartNYT",	"@davidzucchino",	"@TheEastsiderLA",
           "@AJEnglish",	"@howardblume",	"@Richie_Duchon",	"@taygoldenstein",	"@TayeDiggs",	"@latimestravel",	"@mrcsreynolds",
           "@CatHamm",	"@LACMA",	"@eva_recinos",	"@Baxter",	"@NatGeo",	"@billmaher",	"@mattyglesias",	"@mollyesque",	"@rupertmurdoch",
           "@jackshafer",	"@pourmecoffee",	"@NickRiccardi",	"@LAPDChiefBeck",	"@PatriceRoe91701",	"@Salon",	"@TheRyanParker",
           "@THR",	"@LATHeroComplex",	"@SteveSoboroff",	"@sal19",	"@mayasugarman",	"@AlbertLeeInLA",	"@ThePublicSquare",
           "@cmarinucci",	"@RandyLewis2",	"@chrisbarton",	"@emilynussbaum",	"@SteveBattaglio",	"@raulroa",	"@nytimesworld",
           "@_ginamcintyre",	"@spencerbakalar",	"@tedlieu",	"@kentnish",	"@jonfavs",	"@jessica_roy",	"@CAexplained",	"@tpetruno",
           "@Vinncent",	"@KenDilanianNBC",	"@LAPressClub",	"@TracyKWilkinson",	"@KTLAnewsdesk",	"@bj_terhune",	"@LATeducation",
           "@ScottGoldLAT",	"@__ChrisLee",	"@traceylien",	"@midwestspitfire",	"@NicoSmedley",	"@Envelope",	"@TheTweetOfGod",
           "@cjwilliamslat",	"@LisaBoone19",	"@kmyp",	"@jglionna",	"@elonmusk",	"@iamjohnoliver",	"@hellobuglers",
           "@Snowden",	"@JamesFallows",	"@JeromeRCampbell",	"@DLeonhardt",	"@camanpour",	"@KnightLAT",	"@NoeleneClark",
           "@blakehounshell",	"@GeBraxton",	"@alanhagman",	"@FoxNews",	"@rcallimachi",	"@wikileaks",	"@AlanZarembo",	"@BobDrogin",
           "@PhilipRucker",	"@SopanDeb",	"@hillelaron",	"@annamphillips",	"@lenadunham",	"@ava",	"@MagicJohnson",	"@ACLU",
           "@TrishListLA",	"@bettyhallock",	"@mrmarkpotts",	"@CAL_FIRE",	"@thegeowilhelm",	"@CalSunday",	"@DEADLINE",
           "@KatyTurNBC",	"@michaelluo",	"@Bill80",	"@marclacey",	"@McCulloughTimes",	"@DanielMorain",	"@olundp",	"@jrkoren",
           "@ocregister",	"@lpolgreen",	"@LevinsonJessica",	"@nicsperling",	"@therealchouse",	"@CartoonKahuna",	"@NWSLosAngeles",
           "@CHPsouthern",	"@LATdailymirror",	"@USATODAY",	"@StateDept",	"@thehill",	"@BernieSanders",	"@PmcdonnellLAT",	"@Acosta",
           "@GavinNewsom",	"@sree",	"@tomhanks",	"@Dodgers",	"@dexdigi",	"@dainabethcita",	"@StoltzeFrankly",	"@kscottLAatlarge",
           "@rebeccatrounson",	"@MVignoles",	"@JasonHNeubert",	"@LindseyThiry",	"@911LAPD",	"@makedaeaster",	"@Pontifex",
           "@ShaneGoldmacher",	"@DavidCloudLAT",	"@jaclyncosgrove",	"@latimeshomicide",	"@CapitolAlert",	"@bcgoyette",	"@ErikWemple",
           "@Booth",	"@BeschlossDC",	"@latimeshome",	"@CharlesMcNulty",	"@CALFIRE_PIO",	"@RajaAbdulrahim",	"@metrolosangeles",	"@GlennKoenig",
           "@Publici",	"@PolitiFact",	"@mmcphate",	"@SenSanders",	"@davidhorsey",	"@Jerryhirsch",	"@mlcalderone",	"@CaliforniaWatch",
           "@latimesfirehose",	"@AoDespair",	"@Newsweek",	"@MichaelMcGough3",	"@Bourdain",	"@tracycbrown",	"@NewsHour",	"@pfal",
           "@DavidCornDC",	"@hiddenla",	"@UpshotNYT",	"@AshleyRParker",	"@brandigrissom",	"@JuddApatow",	"@KCET",	"@AlbertBrooks",
           "@borzou",	"@edmundsanders",	"@nybooks",	"@BetsySharkey",	"@gary_coronado",	"@margotroosevelt",	"@LATimesGraphics",
           "@edatpost",	"@thebenbergman",	"@MarkLeibovich",	"@ditzkoff",	"@mtaibbi",	"@jdickerson",	"@poniewozik",	"@LATimesWharton",
           "@amyschumer",	"@FBI",	"@thenation",	"@susanorlean",	"@jimmykimmel",	"@lasdNicole",	"@yashar",	"@JohnCanalis",	"@elizabethforma",
           "@TMZ",	"@FOXLA",	"@BostonGlobe",	"@IRE_NICAR",	"@Twitter",	"@DavidGSavage",	"@JeffreyGoldberg",	"@adamelmahrek",
           "@zahiratorres",	"@samquinones7",	"@jguynn",	"@pedromoura",	"@bermudezsa",	"@Schwarzenegger",	"@LATenvironment",
           "@c_kirkham",	"@BlakeHennon",	"@ONA",	"@nytpolitics",	"@ajam",	"@ForeignPolicy",	"@mikiebarb",	"@Yamiche",	"@DelWilber",
           "@joannalin",	"@NYTOnIt",	"@jonathanchait",	"@roberthilburn",	"@SandyBanksLA",	"@HenryHChu",	"@kbaxter11",
           "@DavidMuronaka",	"@MelissaLeu",	"@NPRextra",	"@business",	"@reallisa",	"@latimesobits",	"@BorowitzReport",
           "@karaswisher",	"@TheMadBrand",	"@bytimlogan",	"@marcmaron",	"@latimesfob",	"@JillAbramson",	"@flyLAXairport",
           "@MarkHalperin",	"@latimesmmiller",	"@ladailynews",	"@Max_Fisher",	"@niemanstory",	"@KTLAMorningNews",	"@Mike_Bresnahan",
           "@LATimesklein",	"@earthquakesLA",	"@jeffzeleny",	"@davidsiders",	"@alexburnsNYT",	"@jbouie",	"@nathanmasters",
           "@sirenevirbila",	"@sarahardalani",	"@BillSimmons",	"@WWLA",	"@acolby",	"@NYTmag",	"@RollingStone",	"@sherrystern",
           "@NikkiFinke",	"@leemargulies",	"@LATcelebs",	"@LAFDtalk",	"@lisabiagiotti",	"@jackiekcalmes",	"@thegarance",
           "@lacfd",	"@ActuallyNPH",	"@latimesjlc",	"@latsondheimer",	"@DufRankman",	"@mrcsreynolds",	"@LADeadline16",
           "@LindaRogersLA",	"@sdut",	"@jk_rowling",	"@MarshallProj",	"@danbalz",	"@mjmishak",	"@jahree",	"@kairyssdal",
           "@frankrichny",	"@latimesquakes",	"@markknoller",	"@richardrushfield",	"@zhelfand",	"@LosFelizDaycare",	"@ewooLA2015",
           "@EW",	"@marcbernardin",	"@ebertchicago",	"@joshtpm",	"@dynamofire",	"@enhowe",	"@cnni",	"@dhgerson",	"@verge",
           "@jodikantor",	"@KellyannePolls",	"@GStephanopoulos",	"@richtpau",	"@ryanjreilly",	"@LATunleashed",	"@AirTalk",
           "@NPR-L.A.",	"@AHMalcolm",	"@AliciaDotBanks",	"@tiffmkelly",	"@LaurenEBeale",	"@mlittlesf",	"@NPRinskeep",	"@mmacvean",
           "@Wesley_Morris",	"@sethmeyers",	"@latimesimage",	"@helenenothelen",	"@PeteSouza44",	"@EdJoyce",	"@LATstephanie",
           "@maryforgione",	"@harrysonpics",	"@mikejames1971",	"@JZarracina",	"@AFP",	"@SoCalNewsGuy",	"@christinezhang",
           "@MarsCuriosity",	"@VP",	"@Oprah",	"@GeneMaddaus",	"@PulitzerPrize",	"@julietlapidos",	"@SamSifton",	"@vulture",
           "@latimesfunland",	"@rickygervais",	"@Grantland33",	"@LAReviewofBooks",	"@NTSB",	"@michaelpollan",	"@KarleneGoller",
           "@cnakano",	"@annkpowers",	"@ScottCollins",	"@mplasd",	"@brainpicker",	"@samstein",	"@JessicaQChen",	"@VICE",
           "@vicenews",	"@kumailn",	"@Lin_Manuel",	"@latimesfires",	"@PressSec44",	"@MittRomney",	"@latimeshaiku",
           "@latimesmoneyco",	"@dougmcgray",	"@popupmag",	"@calsunday",	"@Deadspin",	"@SHAQ",	"@PHongAngeleno",
           "@byjessekatz",	"@SethMacFarlane",	"@LAasSubject",	"@PBS",	"@mitchellreports",	"@NYMag",	"@ReutersThevenot",	"@neelaeast",
           "@writerchica",	"@kobebryant",	"@sonaiyak",	"@MerriamWebster",	"@guardiannews",	"@LARegisterNews",	"@DanCALmatters",
           "@anamariecox",	"@RunGomez",	"@joannaclay",	"@andyroberson22",	"@AlecMacGillis",	"@carolynryan",	"@jelani9",
           "@BoomCalifornia",	"@LATrealestate",	"@meghan_daum",	"@fsgbooks",	"@PicadorUSA",	"@BraddJaffy",	"@wpjenna",
           "@dalinac",	"@ariannahuff",	"@SFGate",	"@webjournalist",	"@Scaramucci",	"@FrankBruni",	"@RogerAinsley",
           "@AnnCurry",	"@DavidNgLAT",	"@GeorgeTakei",	"@ogettell",	"@espn",	"@AnnaKendrick47",	"@nxthompson",	"@TechCrunch",
           "@jbarro",	"@ThisAmerLife",	"@deray",	"@ccadelago",	"@adamgoldmanNYT",	"@markkatches",	"@latimeslive",	"@jonweisman",
           "@kimbui",	"@HowardKurtz",	"@annfriedman",	"@DalaiLama",	"@KeithOlbermann",	"@JillCowan",	"@MelodyPetersen",
           "@latbbolch",	"@nprscottsimon",	"@bittman",	"@LADWP",	"@BBCNews",	"@USCAnnenberg",	"@RadioChio",	"@accordingtoAW",
           "@dabeard",	"@KCBSKCALDesk",	"@OCSD",	"@MikeDiGiovanna",	"@MSNBC",	"@RBReich",	"@stevendevol",	"@damiencave",
           "@theintercept",	"@chicagotribune",	"@eaterla",	"@DaveMontero",	"@amychozick",	"@Redistrict",	"@LADAOffice",
           "@USATODAY",	"@AP",	"@maryvale",	"@ndiblasio",	"@nytimes",	"@pmmichalski",	"@BarackObama",	"@SusanPage",
           "@washingtonpost",	"@DonnaLeinwand",	"@JessicaDurando",	"@annieisi",	"@desairbrown",	"@lhorwich",	"@DColtonNow",
           "@jkelly3rd",	"@romenesko",	"@MikeSnider",	"@ShannonRaeGreen",	"@katharinelackey",	"@OUllmann",	"@cnnbrk",
           "@dcallaway",	"@gregorykorte",	"@usatodayvideo",	"@Yamiche",	"@WSJ",	"@joannelipman",	"@usatodaysports",
           "@alia_e",	"@emilygbrown",	"@ThatGirlCarly",	"@HillaryClinton",	"@usatodayDC",	"@singernews",	"@lkramer",	"@politico",
           "@usatodaylife",	"@NPR",	"@mikeallen",	"@AamerISmad",	"@marcodellacava",	"@ForTheWin",	"@rlocker12",	"@npenzenstadler",
           "@jmbacon",	"@brettmolina23",	"@Poynter",	"@caramrich",	"@alexptachick",	"@jmestepa",	"@MaryBowerman",
           "@LizSzabo",	"@alangomez",	"@NateSilver538",	"@bradheath",	"@MrRJervis",	"@khjelmgaard",	"@susmiller",	"@klawls",
           "@andrewpscott",	"@DavidMastio",	"@TweetBrentJones",	"@USATODAYmoney",	"@HollyTMoore",	"@CNN",	"@Reuters",	"@jswartz",
           "@TrevorHughes",	"@fschouten",	"@soledadobrien",	"@POTUS",	"@jeffersongraham",	"@MrJohnRiley",	"@USATODAYcollege",
           "@johnhillkirk",	"@ShayTorie",	"@alisonannyoung",	"@WhiteHouse",	"@BerylLove",	"@realDonaldTrump",	"@TheOnion",
           "@ByRogerYu",	"@katiesmithallen",	"@wwcummings",	"@TimWGardner",	"@POTUS44",	"@JeffZillgitt",	"@lauramandaro",
           "@jguynn",	"@BySteveReilly",	"@BillClinton",	"@BBCBreaking",	"@Gannett",	"@NewYorker",	"@jaketapper",	"@StephenAtHome",
           "@coopallen",	"@lindsdee",	"@remrieder",	"@usatodaytech",	"@ObamaWhiteHouse",	"@HuffPost",	"@roxscott",
           "@gtoppo",	"@NathanBomey",	"@USATOpinion",	"@thegoodcarmah",	"@amwillette",	"@SixSpeedSis",	"@JayneODonnell",
           "@elizacollins1",	"@Brooklynguy55",	"@eweise",	"@cbrennansports",	"@hadleypdxdc",	"@brianstelter",	"@lkauss",
           "@williammwelch",	"@kmccoynyc",	"@mattkrantz",	"@markdubya",	"@ChrisWoodyard",	"@latimes",	"@ezraklein",
           "@NBCNews",	"@SLWeiss",	"@HeidiPrzybyla",	"@ChrissyTerrell",	"@JBNotes",	"@GwenFlanders",	"@jimmichaels",
           "@TaylorMaycan",	"@ProPublica",	"@APStylebook",	"@jodiontheweb",	"@AndreaMandell",	"@jimmyfallon",	"@annoldenburg",
           "@thedailybeast",	"@MikeGottschamer",	"@BuzzFeed",	"@janeomara",	"@gstrauss_",	"@KellySKennedy",	"@ABC",
           "@ByMaryByrne",	"@JamieMottram",	"@andersoncooper",	"@ArienneXOX",	"@wendygreen_",	"@maggieNYT",	"@CBSNews",
           "@BNightengale",	"@NicoleAuerbach",	"@djusatoday",	"@BreakingNews",	"@bykevinj",	"@carolyncerbin",	"@edbaig",
           "@byPeterEisler",	"@kwillis_kim",	"@AndreaMcCarren",	"@CillizzaCNN",	"@BBCWorld",	"@TIME",	"@yourtake",
           "@ByThomasOToole",	"@ByErikBrady",	"@kayare7",	"@Marisol_Bello",	"@MelanieEversley",	"@guygruber",	"@chucktodd",
           "@Slate",	"@nrarmour",	"@Perfiguy",	"@OrenDorell",	"@FLOTUS",	"@PressSec",	"@ConanOBrien",	"@nancytrejos",
           "@byajperez",	"@richardjwolf",	"@maddow",	"@TheDailyShow",	"@dteeuwen",	"@KorinaLopez",	"@MariaTFowler",
           "@NiemanLab",	"@julessnid",	"@jmsiniff",	"@BuzzFeedBen",	"@JimmerWelch",	"@DaviSusan",	"@bylindsayhjones",
           "@ReidCherner",	"@stephmsolis",	"@tvandenbrook",	"@capitalweather",	"@ByTomFrank",	"@byLorenaBlas",	"@JohnWaggoner",
           "@LauraPetrecca",	"@GaryMLevin",	"@themikefoss",	"@ByJoeFleming",	"@TheAtlantic",	"@robinliss",	"@DebBarrington",
           "@hayaelna",	"@SeanRossman",	"@Fahrenthold",	"@BrackSnacks",	"@toryhargro",	"@anthonydb",	"@terryism",	"@usatmpuente",
           "@thehill",	"@TheEconomist",	"@greggzoroya",	"@JarrettBell",	"@ppruitt",	"@voxdotcom",	"@mashable",	"@USATODAYhealth",
           "@briantruitt",	"@usatodaypodcast",	"@business",	"@USATMoore",	"@ccamia",	"@FiveThirtyEight",	"@bethbelton",
           "@NanSanFran",	"@FLOTUS44",	"@BillGates",	"@erick_smith",	"@RachelAxon",	"@DanWolken",	"@joshhafner",
           "@SaraSorcher",	"@LindaDono",	"@lesmil1",	"@BiancoRobert",	"@sam_amick",	"@ashleymaytweets",	"@maeve_mcdermott",
           "@Twitter",	"@byCindyKramer",	"@haleyblum",	"@jaymedeerwester",	"@USATODAYBooks",	"@LedgeKing",	"@treybarrineau",
           "@PressSec44",	"@DonovanSlack",	"@craasch",	"@bsternbe",	"@GabeLacques",	"@KellyWhiteside",	"@RobertKlemko",
           "@cbrioso",	"@eliblumenthal",	"@mhortobagyi",	"@muckrack",	"@ariannahuff",	"@thuanelston",	"@BecsHaller",
           "@mitchellreports",	"@StateDept",	"@daveweigel",	"@whitneymatheson",	"@HDarr",	"@NicSmith312",	"@ByMichelleHealy",
           "@sandyblock",	"@Oprah",	"@Chetc",	"@billkev",	"@TheEllenShow",	"@HowardKurtz",	"@GlennOneal",	"@SteveMartinToGo",
           "@ScottMGleeson",	"@carr2n",	"@anklamfred",	"@steveelfers",	"@guardian",	"@lagrisham",	"@jhascup22",	"@jmosemak",
           "@GlennThrush",	"@hootsuite",	"@hemjhaveri",	"@TessQuinlan",	"@msdc14",	"@espn",	"@usatodayweather",	"@nprpolitics",
           "@chrislhayes",	"@USATGerryAhern",	"@ByDavidMeeks",	"@JFKucinich",	"@jayrosen_nyu",	"@FoxNews",	"@AdamWoodard",
           "@ONA",	"@NYMag",	"@wusa9",	"@CBS, @TEGNA",	"@WIRED",	"@charissejones",	"@davidaxelrod",	"@paulkrugman",	"@NASA",
           "@AmalieNash",	"@MichelleObama",	"@SenWarren",	"@JenniferJJacobs",	"@TodayInTheSky",	"@EddieTimanus",	"@Pontifex",
           "@CLGrossman",	"@BeschlossDC",	"@BillSimmons",	"@dstanglin",	"@NewsHour",	"@ronshine",	"@NatGeo",	"@PatRyanWrites",
           "@Newsweek",	"@Variety",	"@ElysaGardner",	"@PhilipTortora",	"@CupOfPolitics",	"@SimplyChar18",	"@VP",	"@MSNBC",
           "@kenpaulson1",	"@jerrydshriver",	"@AdiJoseph",	"@aNateScott",	"@PostBaron",	"@poverberg",	"@maxinepark",
           "@KingJames",	"@BryAlexand",	"@MotherJones",	"@mcuban",	"@adamshell",	"@freydkin",	"@Deadspin",	"@ChelseaClinton",
           "@jmartNYT",	"@costareports",	"@JesseYomtov",	"@kevin_spain",	"@scott_boeck",	"@ByNateDavis",	"@claudiapuig",
           "@SenJohnMcCain",	"@heoj",	"@kajawhitehouse",	"@nlgill26",	"@ondeadline",	"@usatodaytravel",	"@iamjohnoliver",
           "@hellobuglers",	"@danbalz",	"@SHAQ",	"@GStephanopoulos",	"@DMooreUSAT",	"@julesvideo",	"@TayeDiggs",	"@MikeMSchwartz",
           "@LakenLitman",	"@TomPelissero",	"@CJR",	"@AP_Planner",	"@brucehorovitz",	"@MaryCadden",	"@SenSanders",	"@CoryBooker",
           "@markknoller",	"@PhilipRucker",	"@kesslermichelle",	"@davidgregory",	"@dvergano",	"@davidfolkenflik",	"@dennisvkelly",
           "@EricPrisbell",	"@ninamandell",	"@ByBerkowitz",	"@WesleyLowery",	"@OHnewsroom",	"@VP44",	"@samstein",	"@DavidCornDC",
           "@MarkHalperin",	"@JolieLeeDC",	"@usatodaynfl",	"@pewresearch",	"@JillDLawrence",	"@kathykiely",	"@ErinVKelly",	"@OGTedBerg",
           "@KatyTurNBC",	"@RussPtacek",	"@wbenjaminson",	"@JohnKerry",	"@jaspercolt",	"@billmaher",	"@Casey_Moore",
           "@washingtonian",	"@carolynpesce",	"@TODAYshow",	"@rollcall",	"@elonmusk",	"@Sulliview",	"@bdresher",
           "@SharonJayson",	"@AdamSchefter",	"@NickKristof",	"@nycjim",	"@MatthewDiebel",	"@DavidLeon_Moore",	"@ByGaryMihoces",
           "@KatzM",	"@VanityFair",	"@Salon",	"@Forbes",	"@Medium",	"@Gawker",	"@KFILE",	"@StephenBorelli",	"@KeithOlbermann",
           "@neiltyson",	"@ggreenwald",	"@BernieSanders",	"@JRCarrollNews",	"@CapitalDownload",	"@APSE_sportmedia",	"@chrisschnaars",
           "@barbdelollis",	"@SpeakerBoehner",	"@laura_ungar",	"@SteveAGardner",	"@mlcalderone",	"@TechCrunch",	"@Zlatimeyer",
           "@PBS",	"@VanJones68",	"@ByOliviaBarker",	"@ZekeJMiller",	"@NFL",	"@revieweddotcom",	"@usatodaystyle",	"@katyperry",
           "@cnni",	"@ekiely",	"@jeffzeleny",	"@meganhchan",	"@tomhanks",	"@brian_mansfield",	"@PolitiFact",	"@MeghanHoyer",
           "@DRUDGE_REPORT",	"@DRUDGE",	"@jonnysaraceno",	"@Schrotenboer",	"@mcgarrytim",	"@GeorgeSchroeder",	"@RogersJourno",
           "@Lin_Manuel",	"@tweetAJNK",	"@mcollinsNEWS",	"@mattdpearce",	"@DCist",	"@SportsCenter",	"@Snowden",
           "@TDSbrettkelman",	"@shawnjsullivan",	"@CNBC",	"@jtimberlake",	"@ActuallyNPH",	"@lizkellynelson",	"@jefftayloredits",
           "@Humankindvideos",	"@ktumulty",	"@janicenlloyd",	"@wendykoch",	"@katiecouric",	"@darrenrovell",	"@dshesgreen",
           "@PaulMyerberg",	"@GregPresto",	"@maggiehendricks",	"@Mediabistro",	"@seanlahman",	"@jackshafer",	"@SCOTUSblog",
           "@ngaudiano",	"@smarshall51",	"@THR",	"@DylanByers",	"@TwitterVideo",	"@taylorswift13",	"@JoeBiden",	"@mpob",
           "@alexburnsNYT",	"@sethmeyers",	"@Breznican",	"@Steve_DiMeglio",	"@karaswisher",	"@SarahKSilverman",	"@EllenJHorrow",
           "@jonfavs",	"@SJSamano",	"@usatodaysports"	"@kristen_shilton",	"@jlenahan",	"@suburbspod",	"@CarolMemmott",
           "@rupertmurdoch",	"@megynkelly",	"@IvankaTrump",	"@mindykaling",	"@NBCNightlyNews",	"@people",	"@DavidBaratz",
           "@algore",	"@camanpour",	"@RyanW_Miller",	"@mkraju",	"@LukeRussert",	"@MeetThePress",	"@TPM",	"@dberrygannett",
           "@laurably",	"@anamariecox",	"@dabeard",	"@TwitterNews",	"@KenBurns",	"@scottzucker",	"@EdnaGundersen",	"@rickhampson",
           "@VineCreators",	"@richarddeitsch",	"@sinow",	"@usatodaymlb",	"@Nationals",	"@lenadunham",	"@IzzyGould",	"@gwenifill",
           "@JocelynMcClurg",	"@Publici",	"@IRE_NICAR",	"@edatpost",	"@RachelSmolkin",	"@Acosta",	"@jimmykimmel",	"@nypost",
           "@AJEnglish",	"@NPRextra",	"@GMA",	"@wolfblitzer",	"@CNNSitRoom",	"@NancyPelosi",	"@Google",	"@mwadsworth",
           "@mgroppe",	"@marcorubio",	"@FakeAPStylebook",	"@tylerpager",	"@kasie",	"@SamuelLJackson",	"@SI_PeterKing",
           "@PDavidsonusat",	"@RyanLizza",	"@ESPNStatsInfo",	"@HeatherR_Tucker",	"@Buster_ESPN",	"@ByPeterBarzilai",	"@JayBilas",
           "@Rachel__Nichols",	"@philanap",	"@SopanDeb",	"@AshleyRParker",	"@Scaramucci",	"@wmata",	"@EW",	"@CaraReports",
           "@SInow",	"@elizabeth_shell",	"@bfp_news",	"@RussTorresNYC",	"@cspan",	"@postpolitics",	"@WTOP",	"@DMRegister",
           "@gburton",	"@SpeakerRyan",	"@nytpolitics",	"@MittRomney",	"@CruiseLog",	"@JohnJHarwood",	"@MajorCBS",	"@wanderlust13",
           "@DanWetzel",	"@Pogue",	"@jeffjarvis",	"@jackgillum",	"@jimbrady",	"@kurteichenwald",	"@jack",	"@SportsonEarth",
           "@ByKevinAllen",	"@DanUthman",	"@Ken_Rosenthal",	"@MagicJohnson",	"@mollyesque",	"@sportspsa",	"@mikiebarb",
           "@wojespn",	"@JebBush",	"@CNNPolitics",	"@FBI",	"@postlocal",	"@nbc",	"@newlees_onlife",	"@McKGrant",	"@DalaiLama",
           "@AFP",	"@UN",	"@KimPainter",	"@OKnox",	"@ganjansen",	"@amyewalter",	"@donnabrazile",	"@ktgirl1",	"@BBCNews",
           "@JoyAnnReid",	"@TwitterLive",	"@JoanBiskupic",	"@instagram",	"@YahooForde",	"@lheron",	"@wozerina",	"@BostonGlobe",
           "@CThompsonENQ",	"@almarlatour",	"@Hadas_Gold",	"@BraddJaffy",	"@Comey",	"@Journo_Christal",	"@TheJusticeDept",	"@jonkarl",
           "@Longreads",	"@RollingStone",	"@EricLiptonNYT",	"@davidgcraig",	"@NYinDC",	"@HuffPostPol",	"@FallonTonight",
           "@freep",	"@AnnahBackstrom",	"@ron_fournier",	"@gkicinski",	"@BrophyMarcus",	"@amyschumer",	"@billkeller2014",
           "@LorenzoGReyes",	"@danpfeiffer",	"@garystoller",	"@SenatorReid",	"@brianefallon",	"@orndorfftroyan",	"@tomweirsports",
           "@FireChrisChase",	"@jimhalley",	"@chris_strauss",	"@BobVelin",	"@joshlpeter11",	"@ByMikeJones",	"@andrewrsorkin",
           "@amychozick",	"@peterbakernyt",	"@guardiannews",	"@WSJbreakingnews",	"@PeteSouza44",	"@DeptofDefense",	"@PRyan",
           "@margarettalev",	"@YahooNews",	"@MabintyQ",	"@tim_cook",	"@tsspangler",	"@dcbigjohn",	"@Cbrennan_USAT",
           "@YouTube",	"@mattyglesias",	"@ladygaga",	"@GOP",	"@jonallendc",	"@jdickerson",	"@mmurraypolitics",	"@MLB",
           "@rainnwilson",	"@JeffreyGoldberg",	"@AnnCurry",	"@DRUDGE",	"@SethMacFarlane",	"@funnyordie",	"@grahammt",
           "@waltmossberg",	"@whpresscorps",	"@awfulannouncing",	"@LukeKerrDineen",	"@ByMikeBrehm",	"@nateryan",	"@AshMWill",
           "@SteveCarell",	"@KellyannePolls",	"@JoeNBC",	"@rollcallpols",	"@MHarrisPerry",	"@indystar",	"@ProFootballTalk",
           "@ErikWemple",	"@joshrogin",	"@joshtpm",	"@ghager50",	"@JenniferJolly",	"@CIA",	"@ByLarryCopeland",	"@btrpkc",
           "@maryamb",	"@timkaine",	"@rickygervais",	"@ebertchicago",	"@blakehounshell",	"@ananavarro",	"@HallieJackson",
           "@nbcsnl",	"@aterkel",	"@RichardEngel",	"@elisefoley",	"@jarrad_tweets",	"@RGIII",	"@bill_thornton",	"@ErinAndrews",
           "@ByJimCorbett",	"@tomfriedman",	"@DLeonhardt",	"@LarrySabato",	"@nprscottsimon",	"@KenDilanianNBC",	"@nancihellmich",
           "@quincystreet",	"@MMcCarthyREV",	"@sganim",	"@PeteThamel",	"@jodiupton",	"@AlbertBrooks",	"@dcsportsbog",
           "@JustinAbrotsky",	"@jorgelortiz",	"@JerrySeinfeld",	"@DonGonyea",	"@BorowitzReport",	"@Grantland33",	"@ACLU",
           "@VickiMichaelis",	"@mortreport",	"@spj_tweets",	"@NYDailyNews",	"@businessinsider",	"@wikileaks",	"@MMFlint",
           "@Reince",	"@nytimesworld",	"@azizansari",	"@abbydphillip",	"@vellicott",	"@NikkiBurdine",	"@ashnday",
           "@usatodaymags",	"@thenation",	"@nationaljournal",	"@richardbranson",	"@azcentral",	"@SiriouslySusan",	"@DavidChalian",
           "@marissamayer",	"@ryansholin",	"@NPRinskeep",	"@HowGovtWorks",	"@rickklein",	"@CharlesMBlow",	"@MarkMemmottNPR",
           "@11g",	"@NewJerseyRAG",	"@ajam",	"@MichaelWolffNYC",	"@AaronBlake",	"@KellyO",	"@JenCalfas",	"@chrisgeidner",
           "@UpshotNYT",	"@tackettdc",	"@Newseum",	"@htranbui",	"@Bourdain",	"@andreastonez",	"@chukathy",
           "@OnDeadlineWMel",	"@MikeGarafolo",	"@MarsCuriosity",	"@sallyjenx",	"@Nick_Schwartz",	"@CapehartJ",	"@sree",
           "@JournalistsLike",	"@MarkRuffalo",	"@ABCWorldNews",	"@FT",	"@moody",	"@jk_rowling",	"@HotlineJosh",	"@BresPolitico",
           "@jpaceDC",	"@DCPoliceDept",	"@SpaceX",	"@ONAConf",	"@amywebb",	"@wcp",	"@petridishes",	"@ava",	"@seungminkim",	"@TMZ",
           "@BenMullin",	"@BuzzFeedNews",	"@Ramon_Padilla",	"@mmfa",	"@joanwalsh",	"@Lawrence",	"@TEDTalks",	"@jheil",
           "@yvonnewingett",	"@dannowicki",	"@TDSIanJames",	"@Florida_Today",	"@elizabethforma",	"@judykeen",	"@PeterHamby",
           "@mateagold",	"@HerbNJDC",	"@thegarance",	"@jonathanweisman",	"@seanspicer",	"@FastCompany",	"@joshgerstein",
           "@anniekarni",	"@RobinAria",	"@jbarro",	"@scmicek",	"@pourmecoffee",	"@pattonoswalt",	"@aplusk",	"@maureendowd",
           "@KThomasDC",	"@ap",	"@PreetBharara",	"@sdocjones",	"@RealMikeWilbon",	"@Bharper3407",	"@RJSzczerba",
           "@markpesavento",	"@davidfrum",	"@60Minutes",	"@frontlinepbs",	"@MickLaSalle",	"@Ourand_SBJ",	"@AdamKilgoreWP",
           "@chelsea_janes",	"@jasongay",	"@wpjenna",	"@marksluckie",	"@big_cases",	"@jrnlsm",	"@SecretService",	"@Trevornoah",
           "@kylegriffin1",	"@NWS",	"@vulture",	"@nickbilton",	"@Penserga25",	"@profkrg",	"@duanegang",	"@TheDemocrats",
           "@HardballChris",	"@Eugene_Robinson",	"@Enquirer",	"@TeamUSA",	"@wefollow",	"@businessed",	"@jaysonst",
           "@refineddesigner",	"@michaelscherer",	"@juliemason",	"@LiquidNewsroom",	"@AmbPower44",	"@jfritze",	"@mitchthorson",
           "@cathyapayne",	"@bydanielvictor",	"@newtgingrich",	"@garrettstories",	"@MelissaMHill",	"@courtneydean",
           "@charliesheen",	"@JillAbramson",	"@KevinSpacey",	"@BillKristol",	"@RobinRoberts",	"@USATODAYeats",	"@kobebryant",
           "@cstraight",	"@ivorycomm1",	"@DavidAndelman",	"@Ncholertonbrown",	"@emilynussbaum",	"@BruceLeshan",	"@RapSheet",
           "@nflcommish",	"@verified",	"@NFLprguy",	"@Peggynoonannyc",	"@DHSgov",	"@AriFleischer",	"@derekwillis",
           "@nickconfessore",	"@StationCDRKelly",	"@JeffPassan",	"@jbouie",	"@ChrisKorman",	"@rcallimachi",	"@Olivianuzzi",
           "@mikememoli",	"@woodruffbets",	"@AnnaKendrick47",	"@deirdredonahue",	"@journtoolbox",	"@nprmonkeysee",
           "@bookbobminz",	"@moorehn",	"@FinancialTimes",	"@tedcruz",	"@RandPaul",	"@DanaBashCNN",	"@roberns",	"@DonaldJTrumpJr",
           "@JakeSherman",	"@carolelee",	"@Trysta_Krick",	"@weatherchannel",	"@BleacherReport",	"@nbcwashington",	"@csweigart",
           "@MarsheilaJHayes",	"@SocialInDC",	"@KirstenPowers",	"@morningmika",	"@Olympics",	"@AmbRice44",	"@rihanna",
           "@AsburyParkPress",	"@TheWilderThings",	"@kleinmatic",	"@richeisen",	"@SenateDems",	"@kenvogel",	"@KarlRove",
           "@fmanjoo",	"@nytmike",	"@BFischerMartin",	"@JeffBezos",	"@LindseyGrahamSC",	"@WestWingReport",	"@MarkLeibovich",
           "@DavidNakamura",	"@kwelkernbc",	"@tamarakeithNPR",	"@jameshohmann",	"@politico_45",	"@JSucherman",	"@rcoddington",
           "@davidphinney",	"@GovChristie",	"@pauleberry",	"@travelinreid",	"@SethLivingstone",	"@pgammo",	"@JayGlazer",
           "@ClaytonESPN",	"@lindsayczarniak",	"@JuddApatow",	"@biz",	"@WSJ",	"@murraymatt",	"@RBlumenstein",	"@nytimes",
           "@almarlatour",	"@gerardtbaker",	"@rupertmurdoch",	"@BarackObama",	"@TheEconomist",	"@NewYorker",	"@AP",
           "@dkberman",	"@realDonaldTrump",	"@paulwsj",	"@gabbystern",	"@Reuters",	"@davidmwessel",	"@washingtonpost",
           "@GeraldFSeib",	"@GRogow",	"@wisnefski",	"@business",	"@mikeallen",	"@BruceOrwall",	"@jasongay",	"@geoffreyfowler",
           "@maggieNYT",	"@MtthwRose",	"@davidenrich",	"@AlexMartinWSJ",	"@romenesko",	"@HillaryClinton",	"@WSJbreakingnews",
           "@NateSilver538",	"@POTUS",	"@grainnemcc",	"@cglancey",	"@srussolillo",	"@raju",	"@PaulSonne",	"@BBCBreaking",
           "@delaney",	"@pdacosta",	"@Reddy",	"@greg_ip",	"@TimJHanrahan",	"@cnnbrk",	"@rebeccaballhaus",	"@ProPublica",
           "@charlesforelle",	"@EmmaMoodyWSJ",	"@georgikantchev",	"@mikemillerwsj",	"@RickBrooksWSJ",	"@WSJTech",	"@WSJ",
           "@WSJecon",	"@paulkrugman",	"@jennystrasburg",	"@TheOnion",	"@SamWalkers",	"@DrewDowell",	"@qz",	"@WSJCentralBanks",
           "@antontroian",	"@JoeWSJ",	"@alansmurray",	"@ezraklein",	"@FinancialTimes",	"@NLipschutz",	"@bkesling",
           "@WSJPolitics",	"@POTUS44",	"@danacimilluca",	"@FT",	"@AaronLucchetti",	"@ForsythJenn",	"@DaveCBenoit",	"@mims",
           "@NickTimiraos",	"@LauraStevensWSJ",	"@WSJGraphics",	"@WSJMoneyBeat",	"@NKingofDC",	"@politico",	"@brianstelter",
           "@TheAtlantic",	"@DanaMattioli",	"@WSJbusiness",	"@JamieHeller",	"@ShiraOvide",	"@gadfly",	"@TMannWSJ",
           "@damianpaletta",	"@WhiteHouse",	"@michaelsiconolf",	"@johnjedwards3",	"@sbanjo",	"@lheron",	"@SerenaNgWSJ",
           "@NiemanLab",	"@MatinaStevis",	"@JoannaStern",	"@WomenAtDJ",	"@RachelEnsignWSJ",	"@JohnCarreyrou",	"@GlennHall",
           "@BBCWorld",	"@andrewrsorkin",	"@NPR",	"@JeanneWhalen",	"@johndstoll",	"@jdawsey1",	"@StephenAtHome",	"@Shayndi",
           "@felixsalmon",	"@Fahrenthold",	"@kate_linebaugh",	"@wallernikki",	"@BillClinton",	"@germanotes",	"@CNN",	"@wsjemre",
           "@nicole_hong",	"@yarotrof",	"@RWhelanWSJ",	"@kenbrown12",	"@ObamaWhiteHouse",	"@JChengWSJ",	"@rubinafillion",
           "@philizzo",	"@WSJmarkets",	"@KatyStech",	"@johncbussey",	"@guardian",	"@andypeaps",	"@DevlinBarrett",	"@GZuckerman",
           "@samschech",	"@BretStephensNYT",	"@miriamgottfried",	"@jasonzweigwsj",	"@EmilyGlazerWSJ",	"@reidepstein",	"@carriemelago",
           "@tomgara",	"@julianbarnes",	"@BryFitz",	"@ByronTau",	"@TamerELG",	"@BillPowerWSJ",	"@TimAeppel",	"@TomWrightAsia",
           "@pmarca",	"@MPhillipsWSJ",	"@FiveThirtyEight",	"@PreetaTweets",	"@paulvigna",	"@guerreraf72",	"@jgginlondon",	"@stuwoo",
           "@katie_martin_fx",	"@VanessaOConnell",	"@karaswisher",	"@BuzzFeedBen",	"@jasonrdean",	"@BillGates",	"@lexfenwick",
           "@CRTejada",	"@bobdavis187",	"@NickKristof",	"@CrawCoverage",	"@carr2n",	"@elonmusk",	"@stephengrocer",	"@dumav",
           "@BreakingNews",	"@TheStalwart",	"@Slate",	"@bradleyhope",	"@JENeumann",	"@gksteinhauser",	"@Kate_OKeeffe",	"@edkap",
           "@ScottMAustin",	"@Jessicalessin",	"@Snowden",	"@jaketapper",	"@Poynter",	"@zseward",	"@BrianHershberg",	"@PressSec",
           "@andrewlavallee",	"@DionNissenbaum",	"@jayrosen_nyu",	"@melissakorn",	"@alexfrangos",	"@newley",	"@louiseradnofsky",
           "@SarahMarshall",	"@MikeBloomberg",	"@carlazanoni",	"@EHolmes",	"@carolelee",	"@peterlattman",	"@waltmossberg",
           "@emilysteel",	"@RichardRubinDC",	"@nycjim",	"@NYTLiz",	"@RolfeWinkler",	"@WSJspeakeasy",	"@GlennThrush",	"@dmac1",
           "@fieldproducer",	"@WSJSports",	"@Nouriel",	"@drewfhinshaw",	"@ReutersBiz",	"@mariebeaudette",	"@rcallimachi",
           "@shaneharris",	"@kelseykgee",	"@lisafleisher",	"@michaelkamon",	"@erikholmwsj",	"@charliewwells",	"@WSJAsia",
           "@JBSteins",	"@soledadobrien",	"@felschwartz",	"@MikeSpectorWSJ",	"@ScheckWSJ",	"@jacknicas",	"@MarketWatch",
           "@TheDailyShow",	"@bencasselman",	"@jonostrower",	"@NHendersonWSJ",	"@ianbremmer",	"@eorden",	"@adamentous",
           "@fmanjoo",	"@StephenFidler1",	"@PostBaron",	"@allisonlichter",	"@jwmjournalist",	"@NicoleFriedman",	"@Pervaizistan",
           "@ggreenwald",	"@wadeNYC",	"@dlippman",	"@moorehn",	"@daiwaka",	"@Pontifex",	"@asharma",	"@UjessU",	"@zerohedge",
           "@WSJNY",	"@Birdyword",	"@Spencerjakab",	"@talkingbiznews",	"@LydiaSerota",	"@margheritamvs",	"@Abihabib",
           "@eisingerj",	"@voxdotcom",	"@theofrancis",	"@stefaniei",	"@malas_n",	"@AmyAHarder",	"@kristinapet",	"@JuroOsawa",
           "@TIME",	"@amacker",	"@wsj & @wsjfinreg",	"@CarlBialik",	"@elanazak",	"@natebecker",	"@WSJeurope",	"@joshchin",
           "@mike_w_allen",	"@telisdemos",	"@jensmithWSJ",	"@JessBravin",	"@PaulHannon29",	"@Simon_Nixon",	"@CJR",	"@samdagher",
           "@MatthewPhillips",	"@DLeonhardt",	"@macdonaldajm",	"@Longreads",	"@ReedAlbergotti",	"@realrobcopeland",	"@thoroldb",
           "@davidfrum",	"@UpshotNYT",	"@TammyAudi",	"@patrick1barta",	"@NYMag",	"@LizRappaport",	"@digitalhen",
           "@SaraMurray",	"@BenLeubsdorf",	"@MaximColch",	"@sarasmunoz",	"@jackshafer",	"@erinsusanwhite",	"@AlexandraBerzon",
           "@MMQWalker",	"@BW",	"@jeaneaglesham",	"@EconBizFin",	"@Sulliview",	"@mikejcasey",	"@JoshZumbrun",	"@lburkitt",
           "@WIRED",	"@costareports",	"@nytimesbusiness",	"@PhillipaLJ",	"@GoldRiva",	"@georgia_wells",	"@KMPensiero",
           "@ScottThurm",	"@allisondmorrow",	"@GregBensinger",	"@MattMcBradley",	"@JessePesta",	"@Gawker",	"@amychozick",
           "@daveweigel",	"@DowJones",	"@charleshutzler",	"@jkrim",	"@lizrhoffman",	"@WarrenBuffett",	"@nataliewsj",
           "@ToddBuell",	"@willmauldin",	"@Lingling_Wei",	"@ForeignPolicy",	"@billkeller2014",	"@blakehounshell",	"@RyanLizza",
           "@jacobbunge",	"@dannyyadron",	"@JamesRHagerty",	"@abrownewsj",	"@Justinbaer",	"@AaronBack",	"@DJMatthewDalton",
           "@shalini",	"@barbarachai",	"@mrjohncrowley",	"@WSJsnackbar",	"@CNBC",	"@davidaxelrod",	"@elerianm",
           "@HarrietTorry",	"@michaelsderby",	"@mlcalderone",	"@Amirmizroch",	"@Scaramucci",	"@cammcwhirter",	"@JeffreyGoldberg",
           "@mattyglesias",	"@hblodget",	"@patmcgroarty",	"@LaurenceWith",	"@matt_levine",	"@ConanOBrien",	"@bspegele",
           "@JoshRobinson23",	"@EBernsteinWSJ",	"@vgmac",	"@BCAppelbaum",	"@HuffPost",	"@carney",	"@wikileaks",
           "@AlastairGale",	"@keachhagey",	"@peterbakernyt",	"@JuliaAngwin",	"@tepingchen",	"@KFILE",	"@tomdfonzo",
           "@nohodge",	"@JamesVGrimaldi",	"@betswrites",	"@kowsmann",	"@Ryan_Knutson",	"@yunheekim22",	"@nybooks",
           "@caseysjournal",	"@JustinWolfers",	"@SarahNassauer",	"@jmackin2",	"@ariannahuff",	"@maddow",	"@IAPE1096",
           "@nytmargaret",	"@latimes",	"@garyrosenWSJ",	"@brittanyhite",	"@SMeichtry",	"@WSJThinkTank",	"@KellyCrowWSJ",
           "@eliotwb",	"@dealbook",	"@maureenmfarrell",	"@MarkMaremont",	"@LandersWSJ",	"@MichaelCBender",	"@JoannLublin",
           "@MattJCurtin",	"@wconnors",	"@gonzowsj",	"@DanStrumpf",	"@BillSpindle",	"@cjchivers",	"@lpolgreen",	"@ethanwsj",
           "@DiptiKapadia",	"@annett_tim",	"@tellittoal",	"@tracycorrigan",	"@pattersonscott",	"@IanTalley",	"@lesliejosephs",
           "@BenEisen",	"@chungjoanna",	"@liamdenning",	"@FLOTUS",	"@endacurran",	"@WSJdeals",	"@AndrewTangel",	"@maloneyfiles",
           "@laurenweberWSJ",	"@saraheneedleman",	"@AFP",	"@SpiegelPeter",	"@Videoretired",	"@jonkeegan",	"@cpassariello",
           "@laurnorman",	"@davidluhnow",	"@gnagesh",	"@JosieCox_London",	"@ReformedBroker",	"@ShibaniMahtani",	"@JillAbramson",
           "@BuzzFeed",	"@JNBPage",	"@bethreinhard",	"@sarahportlock",	"@JamesGlynnWSJ",	"@SaabiraC",	"@sharonterlep",
           "@SarahKentWSJ",	"@muckrack",	"@emilynussbaum",	"@WSJheard",	"@clare_ansberry",	"@jasonbellini",	"@Loftus",
           "@davidfolkenflik",	"@ReillyDavid",	"@Carl_C_Icahn",	"@timothywmartin",	"@beckybowers",	"@marcelolprince",	"@jdlahart",
           "@TechCrunch",	"@jenvalentino",	"@DylanByers",	"@ranimolla",	"@federalreserve",	"@deborah_solomon",	"@PreetBharara",
           "@AdamTrot",	"@dseetharaman",	"@BGrueskin",	"@AJEnglish",	"@summer_said",	"@KateDavidson",	"@KirstenGrind",
           "@michaeldrisc",	"@ebenshapiro",	"@planetmoney",	"@jonesashby",	"@mashable",	"@VanityFair",	"@morningmoneyben",
           "@hookjan",	"@EricMorath",	"@nytimesworld",	"@grenm",	"@EEPhillips_WSJ",	"@StateDept",	"@andersoncooper",
           "@Forbes",	"@iamjohnoliver",	"@hellobuglers",	"@MattJarzemsky",	"@saumvaish",	"@hannahdreier",
           "@Neil_Irwin",	"@JBFlint",	"@WSJPR",	"@mayaj",	"@helentbbc",	"@Gorman_Siobhan",	"@OHnewsroom",
           "@trippmickle",	"@evadou",	"@gabrielsherman",	"@TroyMcCee",	"@gefairclough",	"@mikiebarb",
           "@AshleyRParker",	"@MaraGay",	"@joepompeo",	"@janetadamy",	"@PeterWSJ",	"@KatyBurne",	"@JamesFallows",
           "@pewresearch",	"@PhilipRucker",	"@WSJworld",	"@PaulJDavies",	"@jmartNYT",	"@chiaraalbanese",	"@SenWarren",
           "@thedailybeast",	"@jodikantor",	"@LeighWSJ",	"@adriankerr",	"@WSJAmbitiousHrs",	"@kevinroose",	"@businessinsider",
           "@jeffsparshott",	"@paulvieira",	"@laurameckler",	"@margotpatrick",	"@Convertbond",	"@RosenthalRC",	"@APStylebook",
           "@EvelynRusli",	"@katierosman",	"@RichardBarley1",	"@Phred_Dvorak",	"@NBCNews",	"@neiltyson",	"@TomBurtonWSJ",
           "@joe_palazzolo",	"@jbarro",	"@sanityclaus",	"@russellgold",	"@HarvardBiz",	"@PressSec44",	"@michaelwhudson",
           "@nxthompson",	"@MaryLuDC",	"@JMSchles",	"@siobhanehughes",	"@toddjolmstead",	"@sree",	"@GSElevator",	"@NYTOnIt",
           "@stegersaurus",	"@amir",	"@aaronzitner",	"@chucktodd",	"@guardiannews",	"@SopanDeb",	"@AlejandroLazo",
           "@ConorDougherty",	"@Breakingviews",	"@LorettaChao",	"@ColleenMNelson",	"@ryanjtracy",	"@mtaibbi",	"@Recode",
           "@FTAlphaville",	"@HirokoTabuchi",	"@MichelleObama",	"@WizJourn",	"@khadeeja_safdar",	"@FrancescaDonner",	"@SenSanders",
           "@barronsonline",	"@erichschwartzel",	"@sheilawsj",	"@SteveMartinToGo",	"@GEDFIELDS",	"@lionelbarber",	"@rickcarew",
           "@dionnesearcey",	"@CassellBryanLow",	"@TomFairless",	"@SarahKSilverman",	"@VP",	"@ABC",	"@ecb",	"@Bloomberg",
           "@RyanDezember",	"@katekelly",	"@DRUDGE_REPORT",	"@DRUDGE","@tgryta",	"@wsj_douglasj",	"@jolshan",
           "@ChinaRealTime",	"@eosnos",	"@jaysolomon",	"@Max_Fisher",	"@djfroschWSJ",	"@heatherhaddon",	"@jenniferhicks",
           "@WSJCity",	"@A_Grossman",	"@Anthony",	"@jjasonchow",	"@paulmozur",	"@pwonacott",	"@bysarahkrouse",	"@Chao_Deng",
           "@Bachscore",	"@brianjbaskin",	"@nickconfessore",	"@jenniferlevitz",	"@SofiaMcFarland",	"@WSJusnews",
           "@ConCotzias",	"@jack",	"@RobinWigg",	"@rob_barry",	"@MKellyGreene",	"@mia_lamar",	"@JMitchellWSJ",
           "@minzengwsj",	"@nypost",	"@TaylorUmlauf",	"@jbsgreenberg",	"@GoldmanSachs",	"@FLOTUS44",	"@marson_jr",
           "@chrislhayes",	"@Storyful",	"@brkend",	"@LauricellaTom",	"@susannecraig",	"@brendanmoran7",	"@TanyaRivero",
           "@jacobgershman",	"@Ese_Journo",	"@NeilShahWSJ",	"@adamnajberg",	"@PIMCO",	"@MattGoldstein26",	"@donal888",
           "@WSJMag",	"@markgongloff",	"@CGrantWSJ",	"@Peston",	"@jarrardcole",	"@gregorhunter",	"@JohnKerry",
           "@EricLiptonNYT",	"@Lin_Manuel",	"@feliciasonmez",	"@acampoflores",	"@Twitter",	"@ChelseaClinton",	"@NASA",
           "@PGourevitch",	"@anfuller",	"@DavidClinchNews",	"@lenadunham",	"@yoreekoh",	"@LaurenGoode",	"@csstewart",
           "@CraigKarmin",	"@SenJohnMcCain",	"@crampell",	"@mitrakalita",	"@nickbilton",	"@RoryWSJ",	"@jonathanrockoff",
           "@williamsmjw",	"@axios",	"@cjfarley",	"@vbauerlein",	"@KannoYoungs",	"@carlquintanilla",	"@MattFutterman",
           "@aviswanatha",	"@Kris_Maher",	"@weigu",	"@CIA",	"@Peggynoonannyc",	"@IMFNews",	"@AnnieLowrey",	"@LHSummers",
           "@BernieSanders",	"@NYTFridge",	"@tracyalloway",	"@cnni",	"@CillizzaCNN",	"@ForeignAffairs",	"@jonfavs",
           "@alexburnsNYT",	"@jon_kamp",	"@Comey",	"@dianabhenriques",	"@ailworth",	"@benfritz",	"@Preetika_Rana",
           "@tim_cook",	"@Lagarde",	"@WSJLife",	"@MHackman",	"@alexandrascaggs",	"@PekingMike",	"@danielnasaw",	"@echasan",
           "@MikeIsaac",	"@NBisserbe",	"@ReaganBrad",	"@markets",	"@brainpicker",	"@Chris_Whittall",	"@MissShumsky",	"@CFR_org",
           "@camanpour",	"@baoyuan",	"@srabil",	"@aylushka_a",	"@gmorgenson",	"@TinaFuhr",	"@nedlevin",	"@BrookingsInst",
           "@Medium",	"@StephArmour1",	"@vipalmonga",	"@MelanieTrottman",	"@lizzadwoskin",	"@nstamouli",	"@FrancisXRocca",
           "@rebeccadobrien",	"@EliStokols",	"@DanFitzWSJ",	"@mrothfeld",	"@LiYuan6",	"@comradewong",	"@thehill",	"@jonathanweisman",
           "@balldeborah",	"@MaryLaneWSJ",	"@WSJPodcasts",	"@tomkeene",	"@CBSNews",	"@nytmike",	"@littlewern",	"@ZushaElinson",
           "@keithbcollins",	"@bzcohen",	"@LauraKusisto",	"@wjrothman",	"@LyonsNotes",	"@Newsweek",	"@JesseDrucker",
           "@jackycwong",	"@AmbPower44",	"@BorowitzReport",	"@PiaCatton",	"@nat_droz",	"@AlyssaAbkowitz",	"@ElenaCherney",
           "@juliejargon",	"@lesliescism",	"@kathrynlurie",	"@juliaioffe",	"@HeathaT",	"@carolynryan",	"@hrw",	"@Sarahlellison",
           "@KellyannePolls",	"@vicenews",	"@lalpert1",	"@ObsoleteDogma",	"@DaisyMaxey",	"@chrisdieterich",	"@michaelluo",
           "@emilybell",	"@ashleyshuston",	"@DrewFitzGerald",	"@EricHolthaus",	"@WesleyLowery",	"@XHNews",	"@MattCowleyBR",
           "@VranicaWSJ",	"@jonsindreu",	"@WSJ",	"@USTreasury",	"@parisreview",	"@UN",	"@danprimack",	"@PolyaLesova",	"@AnujG1",
           "@markscheffler",	"@candacejackson",	"@evanperez",	"@peter_tl",	"@verge",	"@meganmurp",	"@demetria_g",	"@BBCNews",
           "@zekefturner",	"@fastFT",	"@TokyoWoods",	"@mbrauchli",	"@longform",	"@theintercept",	"@KatyTurNBC",
           "@wright_michael_",	"@joewalkerWSJ",	"@NapolitanoDean",	"@WHorobin",	"@ByChunHan",	"@WSJLogistics",
           "@chris_rexrode",	"@cmatthews9",	"@CorinneAbrams",	"@elizabethforma",	"@mochi_wsj",	"@columbiajourn",
           "@JohnCassidy",	"@nikdeogun",	"@adamgoldmanNYT",	"@economistmeg",	"@kirstendanis",	"@shazna",	"@puiwingtam",
           "@KateMilani",	"@pat_minczeski",	"@MotherJones",	"@perlberg",	"@sara_randazzo",	"@RhiannonHoyle",	"@BraddJaffy",
           "@DavidCornDC",	"@mollyesque",	"@BinkleyOnStyle",	"@cdweaver",	"@WSJexpat",	"@AlanZibel",	"@JeffElder",	"@leHotz",
           "@marissamayer",	"@brianaguilar",	"@annalouiesuss",	"@jk_rowling",	"@conradhackett",	"@nprpolitics",	"@Cezary",
           "@GillianTan",	"@gadfly",	"@Jonnelle",	"@radamsWSJ",	"@jennifer_weiss",	"@CritterDJ",	"@DalaiLama",	"@debkhk",
           "@RuthBenderWSJ",	"@stefaniedioses",	"@StoryHinckley",	"@NewsHour",	"@scottmcalvert",	"@farnazfassihi",
           "@McLainSean",	"@misssaxbys",	"@gwfost",	"@stuartathompson",	"@gillianwong",	"@JenniferJJacobs",	"@NYCTSubway",
           "@jonathanchait",	"@valentinapop",	"@JohnJHarwood",	"@NYCMayorsOffice",	"@Sbenkelman",	"@RobertJShiller",
           "@EconEconomics",	"@MichaelWolffNYC",	"@grynbaum",	"@JamesHookway",	"@glubold",	"@pkafka",	"@ShirleyWang",
           "@Austan_Goolsbee",	"@footnoted",	"@natashakhanhk",	"@WSJ",	"@jrwhalen",	"@RachelFeintzeig",	"@TimOBrien",
           "@BV",	"@Gadfly",	"@NYCMayor",	"@BeschlossDC",	"@ColinCBarr",	"@BetsyMorris2",	"@BustilloM",	"@NYTMetro",
           "@blackrock",	"@lrozen",	"@lamthuyvo",	"@anniekarni",	"@bykowicz",	"@WSJ",	"@arusbridger",	"@DaoOfJ",
           "@BuzzFeedNews",	"@ZekeJMiller",	"@lindsaygellman",	"@jtcorrigan",	"@ritholtz",	"@rayalexsmith",	"@yumikoono",
           "@izakaminska",	"@sullydish",	"@wef",	"@m_delamerced",	"@joseerose616",	"@ABarnardNYT",	"@johnjurg",
           "@louisestory",	"@joshtpm",	"@CynthiaLKoons",	"@jimchair",	"@elliot_bentley",	"@algore",	"@whitegl",
           "@ftfinancenews",	"@benjaminwittes",	"@lawfareblog",	"@monicalangley",	"@Huangplan",	"@jeffzeleny",
           "@SlaughterAM",	"@nytpolitics",	"@NYTmag",	"@USATODAY",	"@Hadas_Gold",	"@MarkHalperin",	"@pourmecoffee",
           "@BowlerDerek",	"@PaulPage",	"@DavidBarboza2",	"@v_dendrinou",	"@WSJBeckey",	"@jbenton",	"@Acosta",	"@mirjordan",
           "@jennablan",	"@artpatnaude",	"@dealbreaker",	"@jimmyfallon",	"@JakeSherman",	"@joelight",	"@MelanieLisa",	"@airhen",
           "@observer",	"@johngapper",	"@WillMHDavies",	"@deanbaquet",	"@TonyFratto",	"@bykevinclark",	"@BBCBusiness",	"@FBI",
           "@amyschumer",	"@SCOTUSblog",	"@djtgallagher",	"@alyrose",	"@Gothamist",	"@HeidiVogt",	"@ErikWemple",
           "@FakeAPStylebook",	"@KaraScannell",	"@WSJdigits",	"@DagmarAalund",	"@pmcdowellsea",	"@AmyDMarcus",
           "@landauro",	"@kejalvyas",	"@estherfung",	"@bittman",	"@kaylatausche",	"@NPRinskeep",	"@pgeitnerWSJ",	"@Nate_Cohn",
           "@akaneotani",	"@MichaelHwrdSaul",	"@SenSchumer",	"@benbernanke",	"@MTA",	"@Michael_Calia",	"@letzing",	"@maxabelson",
           "@washingtonpost",	"@Fahrenthold",	"@PostBaron",	"@nytimes",	"@PhilipRucker",	"@wpjenna",	"@WesleyLowery",
           "@costareports",	"@BarackObama",	"@AP",	"@maggieNYT",	"@edatpost",	"@ktumulty",	"@CillizzaCNN",	"@jfdulac",
           "@ezraklein",	"@realDonaldTrump",	"@Sulliview",	"@daveweigel",	"@NewYorker",	"@romenesko",	"@capitalweather",
           "@NateSilver538",	"@meridak",	"@markberman",	"@jaketapper",	"@danbalz",	"@AshleyRParker",	"@PostRoz",	"@mikeallen",
           "@dabeard",	"@HillaryClinton",	"@ErikWemple",	"@abbydphillip",	"@POTUS",	"@mateagold",	"@NPR",	"@garciaruize",
           "@JeffBezos",	"@brianstelter",	"@petridishes",	"@martyweilwapost",	"@ElaheIzadi",	"@mikedebonis",	"@JoelAchenbach",
           "@PostScottWilson",	"@MrDanZak",	"@CarolLeonnig",	"@TheAtlantic",	"@DavidNakamura",	"@WSJ",	"@stevenjay",
           "@cnnbrk",	"@ProPublica",	"@katiezez",	"@AaronBlake",	"@CarlosLozadaWP",	"@TheOnion",	"@JoeHeim",	"@drewharwell",
           "@postlocal",	"@politico",	"@terri_rupar",	"@pbump",	"@WhiteHouse",	"@POTUS44",	"@GenePark",	"@peterbakernyt",
           "@gregpmiller",	"@GlennThrush",	"@elisaslow",	"@voxdotcom",	"@AnnGerhart",	"@PressSec",	"@Slate",	"@NiemanLab",
           "@adamgoldmanNYT",	"@myhlee",	"@_cingraham",	"@StephenAtHome",	"@CaitJGibson",	"@rkellett",	"@ObamaWhiteHouse",
           "@Poynter",	"@bterris",	"@BuzzFeedBen",	"@eilperin",	"@CNN",	"@Reuters",	"@DPAQreport",	"@jdelreal",	"@jameshohmann",
           "@ishaantharoor",	"@DCist",	"@pkcapitol",	"@WPLyndaRobinson",	"@ahauslohner",	"@tjortenzi",	"@GlennKesslerWP",
           "@agearan",	"@JohnWoodrowCox",	"@SwatiGauri",	"@sarahkaplan48",	"@timcurran_dc",	"@SariHorwitz",	"@mlcalderone",
           "@RyanLizza",	"@cameronbarr",	"@annafifield",	"@jackshafer",	"@farhip",	"@LizSly",	"@jmartNYT",	"@DanEggenWPost",
           "@newsbysamuels",	"@SopanDeb",	"@DanLamothe",	"@WashPostPR",	"@nakashimae",	"@ngjennings",	"@thegarance",
           "@FiveThirtyEight",	"@mccrummenWaPo",	"@AdamBKushner",	"@BillClinton",	"@Krissah30",	"@markdubya",
           "@NickKristof",	"@KFILE",	"@mattzap",	"@MonicaHesse",	"@postpolitics",	"@loriamontgomery",	"@marycjordan",
           "@weymouthk",	"@carr2n",	"@chucktodd",	"@mjcontrera",	"@mollyesque",	"@blakehounshell",	"@TheEconomist",
           "@lisabonos",	"@jimtankersley",	"@MikeMadden",	"@scotusreporter",	"@terrence_mccoy",	"@clintonyates",
           "@AlecMacGillis",	"@geneweingarten",	"@Max_Fisher",	"@BBCBreaking",	"@Milbank",	"@amarimow",	"@GregJaffe",
           "@AmyJBrittain",	"@soledadobrien",	"@jrezaian",	"@MarkLeibovich",	"@JulieATate",	"@ggreenwald",	"@VStMartin",
           "@coryhaik",	"@eliseviebeck",	"@AmyEGardner",	"@RoigFranzia",	"@FLOTUS",	"@realBobWoodward",	"@JulieZauzmer",
           "@Lyons_Press",	"@hankstuever",	"@caitlindewey",	"@BBCWorld",	"@WordsOfSarah",	"@spulliam",	"@sinderbrand",
           "@Longreads",	"@tomsietsema",	"@ksieff",	"@mattyglesias",	"@WaPoSean",	"@semelm",	"@DylanByers",	"@Tmgneff",
           "@katdowns",	"@mikerosenwald",	"@jayrosen_nyu",	"@wcp",	"@arelisrhdz",	"@loriara",	"@AllisonMichs",	"@WPJohnWagner",
           "@JeffreyGoldberg",	"@chicoharlan",	"@UpshotNYT",	"@KatyTurNBC",	"@washingtonian",	"@jrstahl",	"@dataeditor",
           "@ianshapira",	"@adamentous",	"@byaaroncdavis",	"@ThePlumLineGS",	"@svance",	"@brady_dennis",	"@nycjim",
           "@tessamuggeridge",	"@OConnellPostbiz",	"@hermanywong",	"@phoebedoris",	"@Julie_Vit",	"@laurahelmuth",
           "@Chris__Richards",	"@chrislhayes",	"@bartongellman",	"@sullivank",	"@thamburger",	"@marypatflaherty",
           "@Pontifex",	"@jialynnyang",	"@LennyMBernstein",	"@EmGusk",	"@AnupKaphle",	"@KelynSoong",	"@TauhidChappell",
           "@davidfrum",	"@paulschwartzman",	"@mikiebarb",	"@DLeonhardt",	"@PowerPost",	"@wmata",	"@Goldfarb",
           "@rcallimachi",	"@nickconfessore",	"@joshrogin",	"@RobinGivhan",	"@mattdpearce",	"@guardian",	"@DCPoliceDept",
           "@gjbarb",	"@PerryStein",	"@KarenAttiah",	"@davidaxelrod",	"@juliaccarpenter",	"@maddow",	"@PressSec44",
           "@SCOTUSblog",	"@postmetrogirl",	"@bankonjustin",	"@BeschlossDC",	"@davidfolkenflik",	"@BreakingNews",
           "@ericrich",	"@crampell",	"@DevlinBarrett",	"@AmyArgetsinger",	"@paulkrugman",	"@BraddJaffy",	"@juliaioffe",
           "@phscoop",	"@FLOTUS44",	"@TIME",	"@nprpolitics",	"@NickMiroff",	"@NirajC",	"@Snowden",	"@HuffPost",	"@thehill",
           "@Eugene_Robinson",	"@LizSeymour",	"@shearm",	"@rachelweinerwp",	"@latimes",	"@KaylaEpstein",	"@andersoncooper",
           "@CJR",	"@cjchivers",	"@dcsportsbog",	"@mffisher",	"@annekornblut",	"@pourmecoffee",	"@bethreinhard",
           "@JerryMarkon",	"@WashPostLife",	"@jbouie",	"@malitzd",	"@markknoller",	"@TheDailyShow",	"@jdawsey1",
           "@PostGraphics",	"@manifold",	"@billkeller2014",	"@greglinch",	"@OHnewsroom",	"@lydiadepillis",	"@PostEverything",
           "@KellyannePolls",	"@jonathanchait",	"@sallyjenx",	"@MotherJones",	"@ColbyItkowitz",	"@MelissaBell",	"@bethoniebutler",
           "@fmanjoo",	"@PostVideo",	"@sbg1",	"@raju",	"@lpolgreen",	"@BuzzFeed",	"@VP",	"@ZekeJMiller",	"@feliciasonmez",
           "@DavidCornDC",	"@jdickerson",	"@alexlaughs",	"@NYMag",	"@abbyohlheiser",	"@sfcpoll",	"@sarahkliff",	"@CapehartJ",
           "@RonCharles",	"@leloveluck",	"@emmersbrown",	"@JoshWhiteTWP",	"@michaelscherer",	"@emilymbadger",	"@CraigMWhitlock",
           "@petulad",	"@pewresearch",	"@jonfavs",	"@longform",	"@byamberphillips",	"@alexburnsNYT",	"@migold",	"@davidmaraniss",
           "@AnnysWaPo",	"@carolynryan",	"@AdamKilgoreWP",	"@MauraJudkis",	"@mradamtaylor",	"@ABC",	"@IvankaTrump",	"@Comey",
           "@Acosta",	"@PostKranish",	"@wpinvestigates",	"@BoothWilliam",	"@nytpolitics",	"@jjouvenal",	"@benjaminwittes",
           "@lawfareblog",	"@thelilynews",	"@TomJackmanWP",	"@Yamiche",	"@Reinlwapo",	"@abeaujon",	"@michaelbirnbaum",
           "@hannahdreier",	"@jehld",	"@SorayaMcDonald",	"@WIRED",	"@katierogers",	"@eschow",	"@samstein",	"@ConanOBrien",
           "@JamesFallows",	"@EricLiptonNYT",	"@HowardKurtz",	"@timcraigpost",	"@jeffzeleny",	"@benpershing",	"@MichelleObama",
           "@TeddyAmen",	"@thedailybeast",	"@StateDept",	"@londonoe",	"@b_fung",	"@AlexHortonTX",	"@joshtpm",
           "@AlyssaRosenberg",	"@EJDionne",	"@damianpaletta",	"@NPRinskeep",	"@SenWarren",	"@SenSanders",	"@APStylebook",
           "@emilyaheil",	"@timcarman",	"@DRUDGE_REPORT",	"@DRUDGE",	"@partlowj",	"@RachelFeltman",	"@terencesamuel",
           "@gwenifill",	"@peterwallsten",	"@mckaycoppins",	"@NYTmag",	"@WTOP",	"@PostStyle",	"@rcsanchez93",
           "@IgnatiusPost",	"@JohnJHarwood",	"@jennaportnoy",	"@ylanmui",	"@PostSports",	"@libcasey",
           "@ForeignPolicy",	"@Neil_Irwin",	"@NewsHour",	"@anniegowen",	"@missy_ryan",	"@Nate_Cohn",	"@AnnieLowrey",
           "@JasonUkman",	"@Lin_Manuel",	"@karoun",	"@BernieSanders",	"@AJEnglish",	"@Gawker",	"@mkraju",	"@DDaltonBennett",
           "@PoliticsReid",	"@sarahhalzack",	"@SenJohnMcCain",	"@CBSNews",	"@Barbara_Vobejda",	"@Scaramucci",	"@amybwang",
           "@jasondhorowitz",	"@niaCNN",	"@smekhennet",	"@rajivscribe",	"@deray",	"@ryanjreilly",	"@mboorstein",	"@DavidSFallis",
           "@JillAbramson",	"@gabrielsherman",	"@AnnHornaday",	"@thewanreport",	"@Hadas_Gold",	"@jbarro",	"@RosieGray",
           "@geoffedgers",	"@PoPville",	"@nbcwashington",	"@Eugene_Scott",	"@jodikantor",	"@FoxNews",	"@Olivianuzzi",
           "@DeNeenLBrown",	"@emilynussbaum",	"@sandhyawp",	"@emily_wax",	"@RickMaese",	"@jonathanweisman",	"@Wonkblog",
           "@ThomasBoswellWP",	"@MittRomney",	"@amyjoyce_berg",	"@htsuka",	"@renaemerle",	"@emilyrauhala",	"@TracyJan",
           "@danapriest",	"@slarimer",	"@lrozen",	"@michikokakutani",	"@kelsey_snell",	"@mviser",	"@MarkHalperin",
           "@JakeSherman",	"@NBCNews",	"@mitchellreports",	"@wapodavenport",	"@angelafritz",	"@mbgelman",	"@bylenasun",
           "@LovedayM",	"@elisefoley",	"@ceciliakang",	"@BillGates",	"@neiltyson",	"@PolitiFact",	"@bydarrylfears",
           "@NASA",	"@FenitN",	"@mnorton",	"@CoryBooker",	"@DafnaLinzer",	"@ariannahuff",	"@mindykaling",	"@JoeNBC",
           "@josephjames",	"@TheUndefeated",	"@amychozick",	"@nytimesworld",	"@JohnKelly",	"@charlie_savage",	"@barrysvrluga",
           "@Bencjacobs",	"@thegoodcarmah",	"@griffwitte",	"@VP44",	"@attackerman",	"@anamariecox",	"@kylegriffin1",
           "@PeteSouza44",	"@chriscmooney",	"@chelsea_janes",	"@marcorubio",	"@martinepowers",	"@mariaglod",	"@Medium",
           "@nhannahjones",	"@karaswisher",	"@jelani9",	"@PreetBharara",	"@kimberlykindy",	"@SteveMartinToGo",	"@wikileaks",
           "@JanellRoss",	"@KamenIntheLoop",	"@robferdman",	"@amzam",	"@gbrockell",	"@karinbrulliard",	"@dandrezner",
           "@lizzieohreally",	"@ACLU",	"@iamjohnoliver",	"@hellobuglers",	"@raghavanWaPo",	"@WaPoFood",	"@ONA",
           "@EmilyYahr",	"@FrancesSSellers",	"@ScottHigham1",	"@JenniferJJacobs",	"@JoyAnnReid",	"@erinmcunningham",	"@jimmyfallon",
           "@drgridlock",	"@SpeakerRyan",	"@adegrandpre",	"@AnaSwanson",	"@ByronTau",	"@theintercept",	"@shaneharris",
           "@FakeAPStylebook",	"@DonaldJTrumpJr",	"@yashar",	"@Metrorailinfo",	"@masumaahuja",	"@willsommer",	"@jribas",
           "@mariasacchetti",	"@BCAppelbaum",	"@nytmike",	"@KunkleFredrick",	"@PeterHamby",	"@mike_pence",	"@FishbowlDC",
           "@CarrieCamillo",	"@deeinphoto",	"@TPM",	"@nybooks",	"@ddale8",	"@NPRextra",	"@SlaughterAM",	"@amandahess",
           "@lheron",	"@StevenMufson",	"@business",	"@Nationals",	"@Deadspin",	"@PostWorldNews",	"@Jonnelle",
           "@lindseybever",	"@ebruenig",	"@ron_fournier",	"@nxthompson",	"@BostonGlobe",	"@tanyasic",	"@Mcely",
           "@McCartneyWP",	"@AdamSerwer",	"@bcleve19",	"@ChelseaClinton",	"@_jeffguo",	"@abhabhattarai",	"@ananavarro",
           "@tnyCloseRead",	"@mbrauchli",	"@kasie",	"@frontlinepbs",	"@davidgregory",	"@lily_cunningham",	"@camanpour",
           "@dcbigjohn",	"@GuinnessKebab",	"@goingoutguide",	"@GStephanopoulos",	"@Anthony",	"@WashPostDC",	"@juliabeizer",
           "@MikeMillerDC",	"@aterkel",	"@JoeYonan",	"@AprilDRyan",	"@DanaBashCNN",	"@dcfireems",	"@vikkie",	"@jackgillum",
           "@ByLynhBui",	"@comicriffs",	"@BuzzFeedNews",	"@joseiswriting",	"@simondenyer",	"@brianefallon",	"@ZoeannMurphy",
           "@jforsythe23",	"@keithlalexander",	"@mashable",	"@axios",	"@seanspicer",	"@richleiby",	"@CindyBoren",
           "@whitneyshefte",	"@rubycramer",	"@jpaceDC",	"@katherinemiller",	"@darth",	"@irin",	"@SangerNYT",	"@SpeakerBoehner",
           "@NewsSue",	"@mattapuzzo",	"@ObsoleteDogma",	"@chrisgeidner",	"@ashleyfeinberg",	"@newrepublic",	"@jonkarl",
           "@JohnKerry",	"@Swerdlick",	"@jakesilverstein",	"@SingletaryM",	"@USATODAY",	"@RachelMan2",	"@bythomasjohnson",
           "@JFKucinich",	"@RonanFarrow",	"@MikeWiseguy",	"@rachel_dry",	"@JebBush",	"@elonmusk",	"@NatGeo",	"@LukeRussert",
           "@ByMoriah",	"@SimonesNews",	"@ClaraJeffery",	"@irishgal09",	"@radleybalko",	"@zpincusroth",	"@Redistrict",
           "@azizansari",	"@Evan_McMullin",	"@pw_cunningham",	"@peterjholley",	"@jimbrady",	"@billy_penn"	"@denverite",
           "@theinclinepgh", 	"@Reince",	"@ajchavar",	"@KevinUhrm",	"@ARothWP",	"@cspan",	"@ryanbeckwith",	"@PeterFinnWP",
           "@tomsherwood",	"@TheWillHobson",	"@lalamasala",	"@faizsays",	"@rickklein",	"@hiattf",	"@iamcarolbeth",
           "@arishapiro",	"@davidfilipov",	"@elizabethforma",	"@AFP",	"@PostPolls",	"@Grantland33",	"@BillSimmons",	"@EricTrump",
           "@kristinegWP",	"@MarkWarner",	"@lizclarketweet",	"@MarshallProj",	"@BenjySarlin",	"@OKnox",	"@eosnos",	"@amyewalter",
           "@DaveSheinin",	"@JamilSmith",	"@JobyWarrick",	"@ThisAmerLife",	"@lenadunham",	"@timkaine",	"@byaliceli",
           "@jenniferamur",	"@unsuckdcmetro",	"@maureendowd",	"@deanbaquet",	"@JoeBiden",	"@CMorelloWP",	"@kenvogel",
           "@ditzkoff",	"@kojoshow",	"@JRubinBlogger",	"@megynkelly",	"@maustermuhle",	"@FBI",	"@VanityFair",	"@Monica_Akhtar",
           "@jayneore",	"@DorisTruong",	"@marcambinder",	"@hillhulse",	"@jimrutenberg",	"@AoDespair",	"@LarrySabato",
           "@DouthatNYT",	"@AmbPower44",	"@HotlineJosh",	"@GrahamDavidA",	"@BrookingsInst",	"@Salon",	"@dlippman",
           "@Bourdain",	"@samsanders",	"@Newsweek",	"@woodruffbets",	"@Publici",	"@GeeDee215",	"@katz",	"@BillKristol",
           "@MajorCBS",	"@HallieJackson",	"@rollcall",	"@thiedee",	"@emilybell",	"@JacksonDiehl",	"@KatrinaNation",
           "@DelWilber",	"@MerriamWebster",	"@jimsciutto",	"@Anthony_Faiola",	"@McFaul",	"@jk_rowling",	"@donnabrazile",
           "@wpmagazine",	"@AP_Oddities",	"@tedcruz",	"@jeneps",	"@juliehdavis",	"@dmontyjr",	"@EvMason",	"@TheRickWilson",
           "@MiriamElder",	"@ABarnardNYT",	"@michaelluo",	"@kimbriellwapo",	"@TheStoryline",	"@qz",	"@CIA",	"@mattdelong",
           "@jennyrogersDC",	"@benjaminsumner",	"@PeteJamison",	"@PeterWStevenson",	"@RuthMarcus",	"@rtraister",	"@jennydeluxe",
           "@Susan_Hennessey",	"@nationaljournal",	"@StevenTDennis",	"@KateNocera",	"@muckrack",	"@jonlovett",	"@pressfreedom",
           "@CharlesMBlow",	"@SchneiderG",	"@NancyPelosi",	"@maxbearak",	"@derekwillis",	"@alexismadrigal",	"@christinawilkie",
           "@susanorlean",	"@jheil",	"@newtgingrich",	"@moody",	"@rupertmurdoch",	"@jeremyscahill",	"@sewellchan",
           "@jasonaldag",	"@valeriestrauss",	"@MarkMazzettiNYT",	"@MSNBC",	"@theamyking",	"@SenSchumer",	"@fritzhahn",
           "@laurenduca",	"@MaxEhrenfreund",	"@spaydl",	"@SabrinaSiddiqui",	"@adamnagourney",	"@JeffreyToobin",	"@anniekarni",
           "@danpfeiffer",	"@rgay",	"@LVozzella",	"@jorgecastillo",	"@mattvita",	"@kheller",	"@jaconi",	"@j_fuller",
           "@CleveWootson",	"@dylanmatt",	"@justinwmmoyer",	"@marksluckie",	"@morningmoneyben",	"@aseitzwald",	"@DavidGrann",
           "@frankrichny",	"@SarahKSilverman",	"@mccarthyryanj",	"@TamerELG",	"@MarieEOliver",	"@MelindaKCMO",	"@vptwritenow",
           "@amyellisnutt",	"@SusanPage",	"@billmaher",	"@JoshuaGreen",	"@sree",	"@felixsalmon",	"@michaelcrowley",	"@ddknyt",
           "@richarddeitsch",	"@sinow",	"@ByJamesWagner",	"@NYTOnIt",	"@TimHerrera",	"@jeremybowers",	"@brainpicker",
           "@Newseum",	"@joshgerstein",	"@joshledermanAP",	"@petersagal",	"@WaPoVanessa",	"@psullivan1",	"@schmidtsam7",
           "@maxjrosenthal",	"@KerryLauerman",	"@SBHendrix",	"@JessicaValenti",	"@byHeatherLong",	"@ThomasErdbrink",
           "@sullydish",	"@postlive",	"@LyndseyLayton",	"@wapodesign",	"@PulitzerPrize",	"@emilybazelon",
           "@anneapplebaum",	"@hunterschwarz",	"@palafo",	"@lizzadwoskin",	"@Indira_L",	"@MurielBowser",	"@bonniebenwick",
           "@morsedan",	"@chefjoseandres",	"@statedeptspox"]